### ISSUE TITLE
Intel and nvidia icons are missing

### ISSUE THREAD

**Issue by miguelangellv** [Shatur/optimus-manager-qt#1]
I installed the package from AUR and the prime-intel and prime-nivida icons are missing, and I don't see in the repository

**Comment by Shatur** [comment]
`prime-intel` and `prime-intel` are icons from the theme. Most likely, your theme simply does not have this icons. For example, in [this](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) theme they are present. Just go to the settings and specify the path to any icon that you like :)

Also unfortunately, in version 1.0 there is a bug, when in the absence of these icons, you will have a transparent icon in the tray. It has already been fixed, there will be no such problem in the next release.

**Comment by Shatur** [comment]
I decided that the standard icons for the system tray are really better to bundle with the application.
