### ISSUE TITLE
Installed HPLIP Optimus Nanager Broken

### ISSUE THREAD

**Issue by cryptodan** [Shatur/optimus-manager-qt#105]
**Bug description**
I have installed HPLIP to use my printer, and after that I am unable to run Optimus manager qt on my system. 

**Steps to reproduce**
Simply installing hplip and python-pyqt5

I expected no breakage

**Environment**

System:
  Kernel: 5.14.9-arch2-1 x86_64 bits: 64 compiler: gcc v: 11.1.0 
  Desktop: Budgie 10.5.3 Distro: Arch Linux 
Machine:
  Type: Laptop System: Notebook product: NH5x_NH7xHP v: N/A serial: <filter> 
  Mobo: Notebook model: NH5x_NH7xHP serial: <filter> UEFI: INSYDE 
  v: 1.07.06rFRE25 date: 08/02/2021 
Battery:
  ID-1: BAT0 charge: 43.8 Wh (100.0%) condition: 43.8/47.2 Wh (92.9%) 
  volts: 16.5 min: 14.4 model: Notebook BAT status: Full 
CPU:
  Info: 8-Core model: 11th Gen Intel Core i7-11800H bits: 64 type: MT MCP 
  arch: Tiger Lake rev: 1 cache: L2: 24 MiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 73744 
  Speed: 3393 MHz min/max: 800/4600 MHz Core speeds (MHz): 1: 3393 2: 1496 
  3: 3822 4: 2963 5: 3716 6: 2599 7: 2649 8: 1514 9: 3341 10: 1689 11: 2682 
  12: 4080 13: 3794 14: 3733 15: 1943 16: 3653 
Graphics:
  Device-1: Intel TigerLake-H GT1 [UHD Graphics] vendor: CLEVO/KAPOK 
  driver: i915 v: kernel bus-ID: 00:02.0 
  Device-2: NVIDIA GA106M [GeForce RTX 3060 Mobile / Max-Q] 
  vendor: CLEVO/KAPOK driver: nvidia v: 470.74 bus-ID: 01:00.0 
  Device-3: Acer BisonCam NB Pro type: USB driver: uvcvideo bus-ID: 1-8:3 
  Display: x11 server: X.Org 1.20.13 driver: loaded: modesetting,nvidia 
  resolution: 1920x1080~144Hz 
  OpenGL: renderer: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 
  v: 4.6.0 NVIDIA 470.74 direct render: Yes 
Audio:
  Device-1: Intel Tiger Lake-H HD Audio vendor: CLEVO/KAPOK 
  driver: snd_hda_intel v: kernel bus-ID: 00:1f.3 
  Device-2: NVIDIA driver: snd_hda_intel v: kernel bus-ID: 01:00.1 
  Sound Server-1: ALSA v: k5.14.9-arch2-1 running: yes 
  Sound Server-2: JACK v: 1.9.19 running: no 
  Sound Server-3: PulseAudio v: 15.0 running: yes 
  Sound Server-4: PipeWire v: 0.3.38 running: no 
Network:
  Device-1: Intel Tiger Lake PCH CNVi WiFi driver: iwlwifi v: kernel 
  port: 5000 bus-ID: 00:14.3 
  IF: wlp0s20f3 state: up mac: <filter> 
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: CLEVO/KAPOK driver: r8169 v: kernel port: 3000 bus-ID: 03:00.0 
  IF: enp3s0 state: down mac: <filter> 
  IF-ID-1: vmnet1 state: unknown speed: N/A duplex: N/A mac: <filter> 
  IF-ID-2: vmnet8 state: unknown speed: N/A duplex: N/A mac: <filter> 
Bluetooth:
  Device-1: Intel AX201 Bluetooth type: USB driver: btusb v: 0.8 
  bus-ID: 1-14:4 
  Report: rfkill ID: hci0 rfk-id: 1 state: up address: see --recommends 
Drives:
  Local Storage: total: 9.55 TiB used: 450.02 GiB (4.6%) 
  ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 980 PRO 500GB 
  size: 465.76 GiB temp: 39.9 C 
  ID-2: /dev/nvme1n1 vendor: Samsung model: SSD 970 EVO Plus 2TB 
  size: 1.82 TiB temp: 43.9 C 
  ID-3: /dev/sda vendor: Samsung model: SSD 870 QVO 8TB size: 7.28 TiB 
Partition:
  ID-1: / size: 393.89 GiB used: 13.29 GiB (3.4%) fs: ext4 
  dev: /dev/nvme0n1p2 
  ID-2: /boot size: 511 MiB used: 54.3 MiB (10.6%) fs: vfat 
  dev: /dev/nvme0n1p1 
  ID-3: /home size: 7.22 TiB used: 369 GiB (5.0%) fs: ext4 dev: /dev/sda1 
Swap:
  ID-1: swap-1 type: partition size: 64 GiB used: 0 KiB (0.0%) 
  dev: /dev/nvme0n1p3 
Sensors:
  System Temperatures: cpu: 52.0 C mobo: N/A 
  Fan Speeds (RPM): N/A 
Repos:
  Packages: 1286 
  Active pacman repo servers in: /etc/pacman.d/mirrorlist 
  1: https://archmirror.it/repos/$repo/os/$arch
  2: https://mirror.erickochen.nl/archlinux/$repo/os/$arch
  3: https://mirror.cyberbits.eu/archlinux/$repo/os/$arch
  4: https://mirror.pseudoform.org/$repo/os/$arch
  5: https://mirror.pkgbuild.com/$repo/os/$arch
  6: https://america.mirror.pkgbuild.com/$repo/os/$arch
  7: https://mirror.lty.me/archlinux/$repo/os/$arch
  8: https://archlinux.uk.mirror.allworldit.com/archlinux/$repo/os/$arch
  9: https://mirror.telepoint.bg/archlinux/$repo/os/$arch
  10: https://archlinux.thaller.ws/$repo/os/$arch
  11: https://mirror.chaoticum.net/arch/$repo/os/$arch
  12: https://phinau.de/arch/$repo/os/$arch
  13: https://arch.mirror.jsc.mx/$repo/os/$arch
  14: https://mirror.cyberbits.asia/archlinux/$repo/os/$arch
  15: https://archimonde.ts.si/archlinux/$repo/os/$arch
  16: https://mirror.cspacehostings.com/archlinux/$repo/os/$arch
  17: https://europe.mirror.pkgbuild.com/$repo/os/$arch
  18: https://asia.mirror.pkgbuild.com/$repo/os/$arch
  19: https://mirror.f4st.host/archlinux/$repo/os/$arch
  20: https://mirror.srv.fail/archlinux/$repo/os/$arch
Info:
  Processes: 395 Uptime: 49m Memory: 31.14 GiB used: 3.32 GiB (10.7%) 
  Init: systemd Compilers: gcc: 11.1.0 Shell: Bash v: 5.1.8 inxi: 3.3.06 

Latest version of Optimus Manager Qt from the aur.

**Comment by Shatur** [comment]
You can't break the app by installing `hplip` and `python-pyqt5`. I assume that something wrong with your system setup. Could you show me the output of the application?

**Comment by cryptodan** [comment]
You can close this I had assumed that since the application icon in my budgie menu was broken that I had assumed that installing my printer broke Optimus manager it works as intended. I enabled startup and it starts up.
