### ISSUE TITLE
Stopped working after recent Manjaro update

### ISSUE THREAD

**Issue by NirmalManoj** [Shatur/optimus-manager-qt#106]
**Bug description**

I have been using optimus-manager-qt to select GPU for processing my display. I have dual monitor setup and I was on GPU only mode. After the recent update today morning, my external monitor doesn't get detected anymore. optimus-manager-qt fails to open. The system tray app is also gone.

**Steps to reproduce**

**Expected behavior**

The GUI of optimus-manager should open as usual and detect my external monitor.

**Screenshots**

**Environment**

-   OS:  Manjaro
-   Desktop environment:  KDE
-   Optimus Manager version:   1.4-1
-   Optimus Manager Qt version:  1.6.4-1

**Additional context**

Please let me know if you need any additional information to find out the problem.

**Comment by Shatur** [comment]
> After the recent update today morning, my external monitor doesn't get detected anymore. optimus-manager-qt fails to open. The system tray app is also gone.

I think the problem has nothing to do with `optimis-manager-qt`, because this application is just an interface for `optimus-manager`.

> Please let me know if you need any additional information to find out the problem.

Run the application in terminal and show me the log.

**Comment by AdmDevSincro** [comment]
I have this after last update

(optimus-manager-qt:7418): Gtk-WARNING **: 05:38:27.524: Theme parsing error: gtk.css:2:103: Failed to import: Error to open the file /usr/share/gnome-shell/extensions/unite@hardpixel.eu/styles/buttons-right/maximized.css: File or directory not exists

**Comment by Shatur** [comment]
> (optimus-manager-qt:7418): Gtk-WARNING **: 05:38:27.524: Theme parsing error: gtk.css:2:103: Failed to import: Error to open the file /usr/share/gnome-shell/extensions/unite@hardpixel.eu/styles/buttons-right/maximized.css: File or directory not exists

It's unrelated.

**Comment by Shatur** [comment]
Duplicate of #108. The issue on the Optimus Manager side.
