### ISSUE TITLE
AMD config template does not save sometimes

### ISSUE THREAD

**Issue by Mario156090** [Shatur/optimus-manager-qt#109]
Hi, it turns out that sometimes when trying to save a configuration via optimus-manager-qt the default tear free section of the AMD section is reset to default. Then optimus-manager.conf blanks the desired configuration in that section.

![image](https://user-images.githubusercontent.com/47507975/146782827-6c3cb790-9f18-4d43-aa63-ebfd3d0d5dcb.png)

**Comment by Shatur** [comment]
Issue template was ignored.
