### ISSUE TITLE
Flatpak for optimus-manager-qt

### ISSUE THREAD

**Issue by ghost** [Shatur/optimus-manager-qt#11]
nice project , i like .
i see ,that this software is not avaible for all the linux distributions ,
would be great ,if you make a flatpak for optimus-manager-qt

https://flathub.org/home

**Comment by Shatur** [comment]
Thank :)
Unfortunately, the project will work only in Arch Linux, because [optimus manager](https://github.com/Askannz/optimus-manager/) backend works only for it.

**Comment by Shatur** [comment]
I assume, that issue can be closed :)
