### ISSUE TITLE
Program doesn't launch 

### ISSUE THREAD

**Issue by KnightKrusty** [Shatur/optimus-manager-qt#110]
**Bug description**
I installed the program using pamac, it installed and when i open the optimus manager app it simply doesnt show any GUI...
i tried to to run it via terminal that doesnt show anything either

I looked into few isssues if someone also had similar issue as mine.. but nothing helped..

```
optimus-manager-qt  
```

![Screenshot_20220124_161847](https://user-images.githubusercontent.com/84474313/150769426-639aa513-9dfe-4d9b-8b9f-e1fae0f70a6a.png)

The optimus-manager works if i switch via cli.. 

optimus-manager --print-mode                                                                                                                                                                          ✔ 
Current GPU mode : integrated

```

● optimus-manager.service - Optimus Manager Commands Daemon
     Loaded: loaded (/usr/lib/systemd/system/optimus-manager.service; enabled; vendor preset: disabled)
     Active: active (running) since Mon 2022-01-24 15:27:07 IST; 49min ago
   Main PID: 1088 (python3)
      Tasks: 1 (limit: 8744)
     Memory: 31.1M
        CPU: 796ms
     CGroup: /system.slice/optimus-manager.service
             └─1088 /usr/bin/python3 -u -m optimus_manager.daemon

Jan 24 15:27:06 HPRYZEN python3[932]: [702] INFO: Available modules: ['nouveau', 'bbswitch', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
Jan 24 15:27:06 HPRYZEN python3[932]: [703] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
Jan 24 15:27:06 HPRYZEN python3[932]: [710] INFO: switching=none, nothing to do
Jan 24 15:27:07 HPRYZEN python3[932]: [740] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
Jan 24 15:27:07 HPRYZEN python3[932]: [740] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20220124T152706', 'requested_mode': 'integrated'}
Jan 24 15:27:07 HPRYZEN python3[932]: [741] INFO: Xorg pre-start hook completed successfully.
Jan 24 15:27:07 HPRYZEN systemd[1]: Started Optimus Manager Commands Daemon.
Jan 24 15:27:07 HPRYZEN python3[1088]: [1] INFO: # Commands daemon
Jan 24 15:27:07 HPRYZEN python3[1088]: [1] INFO: Opening UNIX socket
Jan 24 15:27:07 HPRYZEN python3[1088]: [1] INFO: Awaiting commands


```

**Environment**

-   OS:  Manjaro
-   Desktop environment:  KDE
-   Optimus Manager version:  1.6.4.1
-   Optimus Manager Qt version:  1.4-3

**Comment by Shatur** [comment]
> I looked into few isssues if someone also had similar issue as mine.. but nothing helped..

This means that the application is already stared. Take a look at your system tray.

**Comment by KnightKrusty** [comment]
ohh yes it works...i actually dont use system tray and that is why.. is there any other way to have this widget...

**Comment by Shatur** [comment]
Sorry, but you need system tray to use it.

**Comment by KnightKrusty** [comment]
Ohh ok .. thanks for the help...
