### ISSUE TITLE
Icons are not showing

### ISSUE THREAD

**Issue by MarcusVH98** [Shatur/optimus-manager-qt#112]
**Bug description**
The applet is functionally great, but the icon on the tray is just a void(see far-right in the screenshot), even though I can still right-click it. There's also no icons inside the settings page like the readme is showing.

**Steps to reproduce**
Not sure other than `yay -S optimus-manager-qt`

**Expected behavior**
Icons showing

**Screenshots**
![image](https://user-images.githubusercontent.com/21600027/152856440-ebded3a8-66d9-4343-bf4f-072d324b69aa.png)
![image](https://user-images.githubusercontent.com/21600027/152856474-8dbb5f7c-5e17-4756-bd7d-8c080447ca8b.png)

**Environment**
-   OS: Arch Linux
-   Desktop environment: i3 WM
-   Optimus Manager version: 1.4-3
-   Optimus Manager Qt version: 1.6.4-1

**Comment by Shatur** [comment]
It's because your icons theme (`hicolor` I assume?). Specify paths under `Tray icons` category.

**Comment by MarcusVH98** [comment]
I see. Am I missing something to make it not fetch icons automatically? Tray icons work now, but I can't find a way to get icons in the tray drop-down menu or in the settings page still.

**Comment by Shatur** [comment]
> I see. Am I missing something to make it not fetch icons automatically? Tray icons work now, but I can't find a way to get icons in the tray drop-down menu or in the settings page still.

You just use a stub icon theme that doesn't have the required icons. Try to install any icon theme and the icons will appear.

**Comment by MarcusVH98** [comment]
It's fixed now! I confused myself by only comparing with GTK programs. I set an icon theme for QT with qt5ct and now it works like a charm, just a noob mistake. Thank you for the help.
