### ISSUE TITLE
Bug: icon invalid since 1.6.8

### ISSUE THREAD

**Issue by yanyongyu** [Shatur/optimus-manager-qt#118]
**Bug description**

I just upgraded `optimus-manager-qt` to `1.6.8-1` on AUR, and found `prime-nvidia` and `prime-hybrid` became invalid. I tried to find the icon on my system. it's just exist. I then revert the package to `1.6.7-2` and works fine now.

**Steps to reproduce**

Just upgrade to `1.6.8-1`, `optimus-manager-qt` notified me that icon was invalid.

**Expected behavior**

Show `prime-nvidia` and `prime-hybrid` correctly.

**Screenshots**

Blank icon at traybar and settings panel

**Environment**

-   OS: Manjaro
-   Desktop environment: KDE
-   Optimus Manager version: 1.4-5
-   Optimus Manager Qt version: 1.6.8-1

**Additional context**

**Comment by CorneliusCornbread** [comment]
Seconded, I've been having issues with the icons as well in KDE with the same version of Optimus Manager and QT 
![image](https://user-images.githubusercontent.com/8294697/169306210-65dbee14-82da-496e-a14f-713cae7ceb8f.png)

**Comment by KenwoodFox** [comment]
Yep can confirm ive also got issues 

![image](https://user-images.githubusercontent.com/31870999/169318854-4fa6f1e8-63a9-4641-a991-2526cce39b05.png)

![image](https://user-images.githubusercontent.com/31870999/169318919-db51970b-d9e9-47d6-8532-a18e99b03e4a.png)

**Comment by Shatur** [comment]
Should be fixed with b93ff06881aa1372cd79402a06777bcd5c37def4

Could anyone install `optimus-manager-qt-git` from AUR to confirm?

**Comment by yanyongyu** [comment]
its still invalid for me in `1.6.8.r1.gb93ff06-1`

**Comment by Shatur** [comment]
But it's an old version, you need b93ff06881aa1372cd79402a06777bcd5c37def4

**Comment by Shatur** [comment]
@yanyongyu could you check it again with d39b8362ecd51f2ed644892ccb4f48c07e22cbf6?
Just re-install `optimus-manager-qt-git`.

**Comment by yanyongyu** [comment]
I just tried `d39b836`. It's still invalid :joy:

**Comment by Shatur** [comment]
Okay, how about 51ac3ae500079874eb08b1a6ad8599c7ce13bcc6?

**Comment by yanyongyu** [comment]
it's still invalid. 😭

**Comment by Shatur** [comment]
Probably we shouldn't bundle `index.theme` at all, it breaks tray icon. Pushed d0fd56720b3217d1d3d02163ee736336cdd6f973, could you check it again?

**Comment by yanyongyu** [comment]
it's ok now!!

**Comment by Shatur** [comment]
Great, drafting a new release.
