### ISSUE TITLE
No Optimus Qt in my system tray

### ISSUE THREAD

**Issue by Dametreus** [Shatur/optimus-manager-qt#119]
**Bug description**
Not really sure why this is happening, Im using Garuda Linux (Arch) with the Gnome desktop environment. I Have a system tray extension that seems to work for everything else but not Optimus-Qt, so im not really sure how im suppose to switch between the integrated GPU on my Ryzen 9 5900hx and my RTX 3070M.

**Steps to reproduce**
Ive reinstalled Optimus Manager and Optimus Manager Qt along with making sure I had a system tray extension.

**Expected behavior**
I would think that the Optimus Manager Qt icon would appear in my system tray.

**Environment**

-   OS: (Garuda Linux (Arch)
-   Desktop environment: (GNOME)
-   Optimus Manager version: (1.4-4)
-   Optimus Manager Qt version: (1.6.9-1)

**Additional Comments**
If im being honest im not even sure what GPU is being used or if my steam games are using my RTX 3070M...

**Comment by Shatur** [comment]
I believe I fixed it in #118.

**Comment by ToneyFoxxy** [comment]
You have not, both optimus-manager-qt and optimus-manager-qt-git do not display a tray icon in the GNOME desktop on Arch Linux. On KDE Plasma they seem to be working

**Comment by Shatur** [comment]
Has this worked before in Gnome?

**Comment by ToneyFoxxy** [comment]
I dunno, I have never used GNOME and my friend is new to Linux

**Comment by Shatur** [comment]
Does the tray show other Qt applications?
Like qBitTorrent or KeepassXC.

**Comment by ToneyFoxxy** [comment]
Will check, by the way, thanks for the quick responses Dude

**Comment by ToneyFoxxy** [comment]
I'm sorry for wasting your time, no bug, we made a configuration error

**Comment by Shatur** [comment]
Okay!

**Comment by ToneyFoxxy** [comment]
At least we closed a bug amirite
