### ISSUE TITLE
Tray icon dissapears upon changing wallpaper

### ISSUE THREAD

**Issue by Araly** [Shatur/optimus-manager-qt#12]
I'm using manjaro i3.

I tried having the tray icon launch as I boot i3, like my other icons, like nm-applet for example.But I found that it kept disappearing. I found that it disappears every time I change wallpapers (and i3 starts with a blank wallpaper, and with its startup process, fetches a random wallpaper and applies it).

The process is still running (it's there in htop) so I can't just relaunch the program. I need to kill the process, then launch it again t be able to see the tray icon again.

It's far from a real issue, but as this is supposed to be a nice thing on top of optimus-manager, might as well make it even nicer ^^

**Comment by Shatur** [comment]
Unfortunately, I cannot reproduce this problem on my DE :(
Does the problem occur with other Qt applications?

**Comment by Araly** [comment]
I can't think of other tray icons that use QT, I only have nm-applet, discord, and some audio applet, probably the pulseaudio one. Basically the app stays there and working (I think), but the tray icon dissapears. But because the tray icon is the only way to access the app, I can't do anything with it.

also it's a bit weird that I have to right click the icon for the menu to appear, and the left click does nothing. for that reason I'm more often just running `omn` and `omi`, aliases for the cli that I setup

**Comment by ShaturIQ** [comment]
Could you install and check other applications that use Qt, for example, qBittorrent?

This is because the application does not have a main window, only the settings menu and the tray indicator.

**Comment by Shatur** [comment]
Could you install and check other applications that use Qt, for example, qBittorrent?

This is because the application does not have a main window, only the settings menu and the tray indicator.

**Comment by Araly** [comment]
well, I've been unable to reproduce the issue, so I'll just close it ^^
thanks
