### ISSUE TITLE
Add Icon Options To Gui

### ISSUE THREAD

**Issue by N0madical** [Shatur/optimus-manager-qt#122]
The icons that currently come with the Gui are colorful and don't fit in with a lot of taskbar styles. I propose the addition of the following 16x16 icons as optional icons in the GUI:

![intel](https://user-images.githubusercontent.com/81594278/203234190-a3478342-8e51-4ec3-b521-a40d849e7787.svg)
![nvidia](https://user-images.githubusercontent.com/81594278/203234228-d1a7dce7-71e6-45b1-81e6-7621cc6c9237.svg)
![nvidia-intel-hybrid](https://user-images.githubusercontent.com/81594278/203234238-a31b4fab-b34a-4344-a756-93c5e251b680.svg)

All icons are either designed by me (in the case of the hybrid icon) (I just spliced the Intel and Nvidia icons), or are free-to-use svgs taken off the internet that I edited to fit the 16x16 size and gray-white color scheme.

Intel icon source: https://worldvectorlogo.com/logo/intel-logo
Nvidia icon source: https://seeklogo.com/vector-logo/320015/nvidia

**Comment by N0madical** [comment]
Intel icon source: https://worldvectorlogo.com/logo/intel-logo
Nvidia icon source: https://seeklogo.com/vector-logo/320015/nvidia

**Comment by Shatur** [comment]
These icons should not be overridden by your current theme. Colored icons are versatile because they work with both dark and light themes, which is why I use them by default.
