### ISSUE TITLE
Wrong text in the "Check if daemon is active" error dialogue

### ISSUE THREAD

**Issue by FluffMe** [Shatur/optimus-manager-qt#125]
**Bug description**
The text in the error message that warns about daemon not being active currently reads `The %1 is running.`

It should read `The %1 is not running` instead.

Code: https://github.com/Shatur/optimus-manager-qt/blob/7121c8e334daae0cfcb38909f7a66508a42476a1/src/optimusmanager.cpp#LL192C37-L192C37

Not sure if translations have the same issue.

**Steps to reproduce**
1. Stop the service with `sudo systemctl stop optimus-manager.service`
2. Attempt to switch to Integrated/Hybrid/dGPU.
3. After the confirmation dialogue the error message in question will pop up.

**Expected behavior**
- The string needs to be changed to "The %1 is not running"
- Translations for the string have to be re-checked.

**Screenshots**
![image](https://github.com/Shatur/optimus-manager-qt/assets/1780586/7e38a2b5-c1db-4329-9e53-1303c0de3d3e)

**Environment**
Any

**Additional context**
None

**Comment by Shatur** [comment]
Makes sense! Could you submit a PR?

**Comment by FluffMe** [comment]
Done!

Can do Russian and Ukrainian on crowdin.com with updated .ts or directly.

**Comment by Shatur** [comment]
It would be better if you update it on crowdin, thanks!
