### ISSUE TITLE
Switching doesn't work anymore after upgrade to optimums manager v1.0

### ISSUE THREAD

**Issue by MadScrewdriver** [Shatur/optimus-manager-qt#13]
**Problem**
Switching doesn't work anymore after upgrade to optimums manager v1.0. To switch I have to type "optimus-manager --switch mode". Switching using optimus-manager-qt doesn't work.
After clicking to switch, "journalctl -u optimus-manager" prints:

```
May 27 12:43:13 franciszek-pc python[842]: Received command : intel
May 27 12:43:13 franciszek-pc python[842]: Writing requested mode
```
But nothing happens.

**Laptop**
Lenovo legion y530
Manjaro
Cinnamon
gdm-prime

Thank you!

**Comment by Shatur** [comment]
Does the switch work when you manually logout (after pressing the button in Optimus Manager Qt)?

**Comment by MadScrewdriver** [comment]
It works when I manually logout.

**Comment by Shatur** [comment]
Are you sure that you enable "Automatic logout" in settings on the Optimus tab?

**Comment by MadScrewdriver** [comment]
I have it all enabled ---> https://youtu.be/iwJADUjnO0I

**Comment by Shatur** [comment]
Your video is unavailable :(

Could you try to execute the following:
```
dbus-send --dest=org.gnome.SessionManager /org/gnome/SessionManager 'org.gnome.SessionManager.Logout' uint32:1
```
It must logout you from the current session. Just for test.

**Comment by MadScrewdriver** [comment]
Now it is available, sorry.
The command logout me from the session

**Comment by Shatur** [comment]
Thank you. Strange, I can't reproduce the problem on KDE Plasma (Arch). I'll try to download Manjaro Cinnamon and check it.

**Comment by MadScrewdriver** [comment]
Thanks!, If u need more info, logs from my machine just say it.

**Comment by Shatur** [comment]
Could you compile and run this sample?
Download this files:
[main.cpp](https://pastebin.com/sS7MeDc7)
[Logout.pro](https://pastebin.com/edcGuLNF)
And run the following commands:
```
qmake
make
./Logout
```
Is it logout you from the current session?

**Comment by MadScrewdriver** [comment]
Nothing happens when I run it

**Comment by Shatur** [comment]
Do I understand correctly that the code above does not work, and the command (`dbus-send ...`) works?

**Comment by MadScrewdriver** [comment]
If I understand correctly, yes ---> https://youtu.be/L2yfFjaZ_6Q

**Comment by Shatur** [comment]
Hm... This code, the `dbus-send` and Optimus Manager CLI code are equivalent (executes logout via D-Bus. In older version of Optimus Manager and this tray app logout was executed via daemon. After 1.0 logout must be implemented on the client side.

So it's strange that we can't achieve logout in C++.

**Comment by Shatur** [comment]
Could you show me output from this?
[main.cpp](https://pastebin.com/XDky1gi8)
(Build it with the previous `.pro` file)

And from this variant:
[main.cpp](https://pastebin.com/5BHjMzdh)

**Comment by MadScrewdriver** [comment]
Sorry for my delay, here is output from the first file: 
```
KDE:  false
Gnome:  true
XFCE:  false"
```

and here is from the second:
```
KDE:  false
Gnome:  false
XFCE:  false
```

**Comment by Shatur** [comment]
Lol, just one character, but how many problems: D

Thank you! I will release a new version today.

**Comment by MadScrewdriver** [comment]
Thanks, works like a charm!
