### ISSUE TITLE
Breaks dependency required by optimus-manager-qt

### ISSUE THREAD

**Issue by archlegion** [Shatur/optimus-manager-qt#130]
**Bug description**
I get this, while updating with pacman.
error: failed to prepare transaction (could not satisfy dependencies)
:: installing knotifications5 (5.111.0-1) breaks dependency 'knotifications' required by optimus-manager-qt
:: installing kiconthemes5 (5.111.0-1) breaks dependency 'kiconthemes' required by optimus-manager-qt

-   OS: **Arch Linux x86_64** **6.5.7-arch1-1**
-   Desktop environment:  **KDE Plasma** **5.27.8**
-   Optimus Manager version: **1.5-4**
-   Optimus Manager Qt version: **1.6.9-1**

**Comment by Shatur** [comment]
Please, report AUR related issues on AUR.
