### ISSUE TITLE
Broken generated config for nvidia

### ISSUE THREAD

**Issue by andreisergiu98** [Shatur/optimus-manager-qt#15]
Hello,

When both `Overclocking options` and `Triple buffer` are disabled in app settings, instead of empty string, `@Invalid()` is written to disk.

Like this: 
```
[nvidia]
DPI=96
PAT=yes
modeset=yes
options=@Invalid() 
```

So it breaks the configuration for optimus-manager.

Thx! :)

**Comment by Shatur** [comment]
Thank you, fixed!
