### ISSUE TITLE
Missing icons in settings

### ISSUE THREAD

**Issue by phil294** [Shatur/optimus-manager-qt#18]
xfce, AUR, 1.7.1

While the icons were probably fixed with #1, the settings dialog is still weird (1.7.1):
![](https://i.imgur.com/n4aG8Xw.png)
In the left panel, the icons are missing. In the tray however, they are displayed correctly. And when I click on either of the tray icon selection buttons and click on "cancel":
![](https://i.imgur.com/QlK2S0s.png)
the action is not actually cancelled. The icon gets actually set to "".

But these are only minor annoyances, do not actually matter much. Thought I'd report anyways. :-)

**Comment by Shatur** [comment]
Thanks for the report!
I will fix icon selection, but the icons in settings just missing in your theme :(

**Comment by Shatur** [comment]
What icon theme are you using?

**Comment by phil294** [comment]
I am using [Chicago95](https://github.com/grassmunk/Chicago95/tree/master/Icons/Chicago95)

**Comment by Shatur** [comment]
Fixed, now no missing icons, but in your case you will see default icons. To get more consistent look, send a request to create icons for your theme (you need `intel` and `nvidia` icon).
