### ISSUE TITLE
Switch to Hybrid option is missing

### ISSUE THREAD

**Issue by ttsesm** [Shatur/optimus-manager-qt#20]
Hi @Shatur95 I noticed that in the new update of optimus-manager and optimus-manager-qt it is possible to switch to hybrid where prime render offload is supported. Thus, shouldn't be the option to "Switch to Hybrid" likewise to "Switch ot Intel" and "Switch to Nvidia" once you press right click on the tray icon?

**Comment by Shatur** [comment]
Oh yes, I forgot to add it to the system tray menu :(
Thank you for issue!

**Comment by ttsesm** [comment]
:+1:
