### ISSUE TITLE
Tray icon shows Intel in Hybrid mode

### ISSUE THREAD

**Issue by Ann1kaB** [Shatur/optimus-manager-qt#21]
![Screenshot_20190922_080754](https://user-images.githubusercontent.com/35402073/65386983-2c106d00-dd10-11e9-8c5d-a7bbc10554e2.png)

**Comment by Shatur** [comment]
Hello!
Please, show me the output of the following command:
```bash
optimus-manager --print-mode
```

**Comment by Ann1kaB** [comment]
> Hello!
> Please, show me the output of the following command:
> 
> ```shell
> optimus-manager --print-mode
> ```

![Screenshot_20190923_135343](https://user-images.githubusercontent.com/35402073/65449776-a83aab80-de09-11e9-8bda-be0fd6c9442f.png)
hmm...thats strange that optimus-manager itself detects intel mode, even when its in hybrid mode.
![Screenshot_20190923_135617](https://user-images.githubusercontent.com/35402073/65449921-07002500-de0a-11e9-97c2-80a68cff26b3.png)
this is intel mode, notice no NVIDIA-G0 entry.

**Comment by Shatur** [comment]
Thank you! I will fix it ASAP.
