### ISSUE TITLE
Can't switch to nvidia after upgrade to 1.3.1

### ISSUE THREAD

**Issue by indaleto** [Shatur/optimus-manager-qt#22]
After upgrade to 1.3.1 on Manjaro with Cinnamon I can't switch to nvidia drivers. It through the power management warning, I press "y" to switch but nothing happened.

**Comment by Shatur** [comment]
Do you use Optimus Manager CLI?

**Comment by indaleto** [comment]
No, but to find out what was going on I tried to switch to nvidia through the command line

**Comment by Shatur** [comment]
So do you mean that you can't switch to Nvidia even via with CLI?

**Comment by indaleto** [comment]
Yes

A domingo, 22 de set de 2019, 22:30, Hennadii Chernyshchyk <
notifications@github.com> escreveu:

**Comment by Shatur** [comment]
This repository only for GUI client, not Optimus Manager itself. Please, send this issue to the [Optimus Manager repository](https://github.com/Askannz/optimus-manager/).
