### ISSUE TITLE
Unable to detect GPU after 7172f6a

### ISSUE THREAD

**Issue by Ann1kaB** [Shatur/optimus-manager-qt#23]
![Screenshot_20190924_172033](https://user-images.githubusercontent.com/35402073/65551352-bb27ab80-deef-11e9-9ed4-b7f2f0284c26.png)

**Comment by Shatur** [comment]
Hmm... I think this is because you are using the Intel driver. I did not notice that it has a different name.

**Comment by Shatur** [comment]
Could you check it now?

**Comment by Ann1kaB** [comment]
yup that did it, thank you
