### ISSUE TITLE
The app stopped working

### ISSUE THREAD

**Issue by michaldybczak** [Shatur/optimus-manager-qt#24]
I was using **optimus-manager-qt-git** version successfully for many months on Manjaro testing and a few days ago there was an update of this package.

As I noticed, it added hybrid mode which is nice if someone changed to Nvidia 435 driver series. However, this new version simply won't work. When I tried to switch, session reloads as always and it stays on Intel as before. I tried switching with terminal, all works correctly then.

Switching with with **optimus-manager-qt-git** produced:

```
wrz 24 21:40:08 alienware-PC systemd[1]: Started Optimus Manager Commands Daemon.
wrz 24 21:40:08 alienware-PC python3[909]: Optimus Manager (Daemon) version 1.1
wrz 24 21:40:08 alienware-PC python3[909]: Automatic log cropping
wrz 24 21:40:08 alienware-PC python3[909]: Loading config file
wrz 24 21:40:08 alienware-PC python3[909]: Opening UNIX socket
wrz 24 21:40:08 alienware-PC python3[909]: Awaiting commands
wrz 24 21:41:00 alienware-PC python3[909]: Received command : {
wrz 24 21:41:00 alienware-PC python3[909]:     "args": {
wrz 24 21:41:00 alienware-PC python3[909]:         "mode": "nvidia"
wrz 24 21:41:00 alienware-PC python3[909]:     },
wrz 24 21:41:00 alienware-PC python3[909]:     "type": "switch"
wrz 24 21:41:00 alienware-PC python3[909]: }
wrz 24 21:41:00 alienware-PC python3[909]: Invalid command !
wrz 24 21:41:41 alienware-PC python3[909]: Received command : {
wrz 24 21:41:41 alienware-PC python3[909]:     "args": {
wrz 24 21:41:41 alienware-PC python3[909]:         "mode": "nvidia"
wrz 24 21:41:41 alienware-PC python3[909]:     },
wrz 24 21:41:41 alienware-PC python3[909]:     "type": "switch"
wrz 24 21:41:41 alienware-PC python3[909]: }
wrz 24 21:41:41 alienware-PC python3[909]: Invalid command !
```

So I decided to change startup to Nvidia and... it didn't work either. The system correctly asks for the password and then nothing is changed. Intel is still the default. So basically, none of the actions in the  **optimus-manager-qt-git** worked. Since git versions overwrite it other in pacman cache, there is no way to roll it back.

So the next thing to try was non-git version. It forced uninstalled **optimus-manager-git** as well and replaced it with non-git version too. The result? **optimus-manager-qt** is still not working but it gets worse, it doesn't even start. When I launch it in the terminal I get:

```
Unable to detect GPU
Aborting (segfault)
```
I'm still on 430 drivers if that matters.

I'm switching back to the git version that at least was starting correctly but that was all. I expect that I still can change configs manually so this isn't a big deal, but optimus-manager-qt-git is only a pretty tray icon and nothing more at this point. Too bad, it was a really nice and useful app.
I hope this is a temporary thing.

If you need some additional data to debug it, let me know.

EDIT: After installing git versions again, it's still not starting with the same problem. What is going on? Hmm... I'll try to figure it out.

UPDATE 1: Switching to nvidia mode from terminal works, so optimus-manager is not the problem here. After switching to nvidia, the app suprisingly shows up and I was able to switch through it to Intel, but on Intel session it's not loaded again. It means only Intel session somhow produces this problem.

Still can't make it work on Intel. Here is the status of optimus-manager after reboot (so before any switch attempts):

● optimus-manager.service - Optimus Manager Commands Daemon
   Loaded: loaded (/usr/lib/systemd/system/optimus-manager.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2019-09-26 18:09:24 CEST; 35s ago
  Process: 825 ExecStartPre=/usr/bin/prime-switch-boot (code=exited, status=0/SUCCESS)
 Main PID: 917 (python3)
    Tasks: 1
   Memory: 38.9M
   CGroup: /system.slice/optimus-manager.service
           └─917 /usr/bin/python3 -u /usr/bin/optimus-manager-daemon

```
wrz 26 18:09:23 alienware-PC prime-switch-boot[825]: Loading nouveau module
wrz 26 18:09:24 alienware-PC prime-switch-boot[825]: Loaded extra Intel Xorg options (0 lines)
wrz 26 18:09:24 alienware-PC prime-switch-boot[825]: Loaded extra Nvidia Xorg options (0 lines)
wrz 26 18:09:24 alienware-PC prime-switch-boot[825]: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
wrz 26 18:09:24 alienware-PC systemd[1]: Started Optimus Manager Commands Daemon.
wrz 26 18:09:24 alienware-PC python3[917]: Optimus Manager (Daemon) version 1.2
wrz 26 18:09:24 alienware-PC python3[917]: Automatic log cropping
wrz 26 18:09:24 alienware-PC python3[917]: Loading config file
wrz 26 18:09:24 alienware-PC python3[917]: Opening UNIX socket
wrz 26 18:09:24 alienware-PC python3[917]: Awaiting commands
```

I checked my configs in `/etc/X11/xorg.conf.d/` and `/etc/X11/` and everything is all right, no additional, unwanted configs showed up, only **optimus-manager** is governing the gpu configs, as it should be. So I have no idea why **optimus-manager-qt** (git or non git) is not recognizing it). I may try to restore the recent backup where the app was at least starting correctly, alas it wasn't doing anything aside showing in which mode the desktop is.

**Comment by Shatur** [comment]
Recent versions of Optimus Manager Qt requres the latest version of Optimus Manager, because of this, switching did not work for you (I see the old version of the daemon in the log).
After your update I see that you have the latest version of the Optimus Manager. Do you use the latest version of the Optimus Manager Qt? If yes. could you provide me the output of the `xrandr --listproviders` in Intel mode?

**Comment by michaldybczak** [comment]
Since I re-installed git versions, both apps should be at the newest version, so that settles the first problem with the invalid argument.

Here is the output you asked for:
```
Providers: number : 2
Provider 0: id: 0x7c cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 5 associated providers: 1 name:modesetting
Provider 1: id: 0x44 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 4 outputs: 1 associated providers: 1 name:modesetting
```

Also, I was able to switch back from Nvidia to Intel, so now switching worked but the main issue is now that it's not launching in intel mode because of this "Unable to detect GPU".

I decided to wait a while with rolling back with system backup because I hope I can resolve this issue.

Again I tested it, switched to nvidia from terminal, the tray icon was present in nvidia mode, switched with it to intel correctly, no tray icon. Here is the output:

```
wrz 26 18:09:24 alienware-PC systemd[1]: Started Optimus Manager Commands Daemon.
wrz 26 18:09:24 alienware-PC python3[917]: Optimus Manager (Daemon) version 1.2
wrz 26 18:09:24 alienware-PC python3[917]: Automatic log cropping
wrz 26 18:09:24 alienware-PC python3[917]: Loading config file
wrz 26 18:09:24 alienware-PC python3[917]: Opening UNIX socket
wrz 26 18:09:24 alienware-PC python3[917]: Awaiting commands
wrz 26 23:32:37 alienware-PC python3[917]: Received command : {"type": "switch", "args": {"mode": "nvidia"}}
wrz 26 23:32:37 alienware-PC python3[917]: Writing requested GPU mode nvidia
wrz 26 23:33:11 alienware-PC python3[917]: Received command : {
wrz 26 23:33:11 alienware-PC python3[917]:     "args": {
wrz 26 23:33:11 alienware-PC python3[917]:         "mode": "intel"
wrz 26 23:33:11 alienware-PC python3[917]:     },
wrz 26 23:33:11 alienware-PC python3[917]:     "type": "switch"
wrz 26 23:33:11 alienware-PC python3[917]: }
wrz 26 23:33:11 alienware-PC python3[917]: Writing requested GPU mode intel
```

**Comment by Shatur** [comment]
> Here is the output you asked for

Weird, you have two providers in Intel mode. What is your laptop model?

**Comment by michaldybczak** [comment]
Alienware 17 R3.

I'm not sure if that is not a result of some recent update. Mesa got updated 2 days ago in Manjaro testing. I definitely have just one CPU. Here is more data about the laptop:

Operating System: Manjaro Linux 
KDE Plasma Version: 5.16.5
KDE Frameworks Version: 5.62.0
Qt Version: 5.13.1
Kernel Version: 5.2.17-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 7,7 GiB


```
System:    Host: alienware-PC Kernel: 5.2.17-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.1.0 
           Desktop: KDE Plasma 5.16.5 tk: Qt 5.13.1 wm: kwin_x11 dm: SDDM Distro: Manjaro Linux 
Machine:   Type: Laptop System: Alienware product: Alienware 17 R3 v: 1.7.0 serial: <filter> Chassis: type: 10 
           serial: <filter> 
           Mobo: Alienware model: 0GH72M v: A00 serial: <filter> UEFI: Alienware v: 1.7.0 date: 01/18/2019 
Battery:   ID-1: BAT1 charge: 95.8 Wh condition: 95.8/96.0 Wh (100%) volts: 17.3/15.0 model: COMPAL PABAS0241231 
           serial: <filter> status: Full 
CPU:       Topology: Quad Core model: Intel Core i7-6700HQ bits: 64 type: MT MCP arch: Skylake-S rev: 3 
           L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 41488 
           Speed: 800 MHz min/max: 800/3500 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 801 5: 800 6: 801 7: 800 
           8: 800 
Graphics:  Device-1: Intel HD Graphics 530 vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:191b 
           Device-2: NVIDIA GM204M [GeForce GTX 970M] vendor: Dell driver: nouveau v: kernel bus ID: 01:00.0 
           chip ID: 10de:13d8 
           Display: x11 server: X.Org 1.20.5 driver: modesetting compositor: kwin_x11 tty: N/A 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 530 (Skylake GT2) v: 4.5 Mesa 19.1.7 compat-v: 3.0 
           direct render: Yes 
Audio:     Device-1: Intel 100 Series/C230 Series Family HD Audio vendor: Dell driver: snd_hda_intel v: kernel 
           bus ID: 00:1f.3 chip ID: 8086:a170 
           Sound Server: ALSA v: k5.2.17-1-MANJARO 
Network:   Device-1: Qualcomm Atheros Killer E2400 Gigabit Ethernet driver: alx v: kernel port: d000 bus ID: 3b:00.0 
           chip ID: 1969:e0a1 
           IF: enp59s0 state: down mac: <filter> 
           Device-2: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter vendor: Bigfoot Networks 
           driver: ath10k_pci v: kernel port: d000 bus ID: 3c:00.0 chip ID: 168c:003e 
           IF: wlp60s0 state: up mac: <filter> 
           Device-3: Qualcomm Atheros type: USB driver: btusb bus ID: 1-5:4 chip ID: 0cf3:e300 
Drives:    Local Storage: total: 1.02 TiB used: 749.95 GiB (71.9%) 
           ID-1: /dev/sda vendor: Kingston model: SM2280S3G2120G size: 111.79 GiB speed: 6.0 Gb/s serial: <filter> 
           ID-2: /dev/sdb vendor: HGST (Hitachi) model: HTS721010A9E630 size: 931.51 GiB speed: 6.0 Gb/s 
           serial: <filter> 
RAID:      Hardware-1: Intel 82801 Mobile SATA Controller [RAID mode] driver: ahci v: 3.0 bus ID: 00:17.0 
           chip ID: 8086.282a 
Partition: ID-1: / size: 38.32 GiB used: 33.62 GiB (87.7%) fs: ext4 dev: /dev/sda4 
           ID-2: /home size: 71.26 GiB used: 60.19 GiB (84.5%) fs: ext4 dev: /dev/sda2 
Sensors:   System Temperatures: cpu: 59.0 C mobo: N/A gpu: nouveau temp: 48 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 266 Uptime: 5h 34m Memory: 7.66 GiB used: 2.54 GiB (33.1%) Init: systemd v: 243 Compilers: 
           gcc: 9.1.0 clang: 8.0.1 Shell: bash v: 5.0.11 running in: konsole inxi: 3.0.36 
```

**Comment by Shatur** [comment]
Thank you! I think the problem is in GPU detection algorithm. Could you also provide output of the previous command for NVIDIA mode too?

**Comment by michaldybczak** [comment]
No problem, here:

```
michaldybczak  alienware-PC  ~  xrandr --listproviders
Providers: number : 2
Provider 0: id: 0x244 cap: 0x1, Source Output crtcs: 4 outputs: 1 associated providers: 1 name:NVIDIA-0
Provider 1: id: 0x47 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 5 associated providers: 1 name:modesetting
```

**Comment by Shatur** [comment]
Thanks, could you try the latest git-version again?

**Comment by michaldybczak** [comment]
Awesome! Now it's working again! :+1: 
I tested switching back and forth, changing options, so far no complaints, everything works as intended.
I haven't tested hybrid mode yet because I'm still on 430 driver series and not in hurry to experiment. I'll wait till this off-loading feature matures.
Thank you!
