### ISSUE TITLE
May i know if i need to configuration nvidia and sddm on archlinux

### ISSUE THREAD

**Issue by kktt007** [Shatur/optimus-manager-qt#25]
Archlinux plasma sddm 
I have install nvidia sddm and optimus-manager(have set switching=bbswitch driver=modesetting etc).
May i know if i shoud configure nvidia and sddm somewhere(like defauld/grub /etc/sddm.conf etc).
Many thanks.

**Comment by Shatur** [comment]
No specific configuration for SDDM needed.

**Comment by kktt007** [comment]
> No specific configuration for SDDM needed.

Thank you so much my author. What about nvidia. (configure /etc/default/grub add nvidia-drm.modeset=1  etc.)

**Comment by Shatur** [comment]
You don't need it too.

Also this is repo for GUI interface, please, send such questions to [Optimus Manager repository](https://github.com/Askannz/optimus-manager/).

**Comment by kktt007** [comment]
> You don't need it too.
> 
> Also this is repo for GUI interface, please, send such questions to [Optimus Manager repository](https://github.com/Askannz/optimus-manager/).

I regard here as optimus-manager, sorry.
