### ISSUE TITLE
Settings won't save

### ISSUE THREAD

**Issue by michaldybczak** [Shatur/optimus-manager-qt#28]
For example, when I want to switch Intel from Modesetting to Intel and then try different subsettings, I save it and then check again, nothing has changed, still, modesetting is used.

I probably can change it manually in confs but the GUI should have worked too. I'm unsure if that is just on my side or general bug. How can I debug it?

To be honest, I never played with settings before so I don't know how long this issue exists. I just left it all by default and it was fine. However, with two-monitor setup I noticed synchronization problems that produced weird distortions when watching YouTube on the other monitor. When using nvidia, all those distractions weren't there, all was perfect, so this is happening only on the Intel session. That is why I want to try out other settings to see if it can't be improved. I also must research what is this modesetting anyway. I assumed I use intel drivers so I'm surprised to see modesetting as a driver.

Or actually, if the settings are supposed to change `/etc/optimus-manager/optimus-manager.conf `shouldn't I be asked for sudo or root password? I get no such thing and that is most likely why the settings won't save. The lack of proper rights. So now the question is, why I won't get authorization pop-up?

Thanks.

EDIT: I did change the settings manually, optimus-manager-qt sees it correctly. So in the backed it all works fine but the issue remains: optimus-manager-qt does not ask for sudo/root credentials and is unable to save any changes made to settings.

**Comment by Shatur** [comment]
Have you tried installing the GUI and daemon with the latest commits?

**Comment by michaldybczak** [comment]
I updated it probably a week ago but found today new updates so I installed them, rebooted and now it works! :)
I don't get the sudo/root question but the settings are saved nonetheless.
Thanks :+1:

**Comment by Shatur** [comment]
Please, always use the latest Optimus Manager daemon version when you using the latest version of GUI.
At the moment, the GUI uses a new mechanism for saving settings, which added in the latest Optimus Manager daemon commits.

**Comment by michaldybczak** [comment]
I know. It's because the previous update was not so long ago I assumed I have the latest commits. I forgot how quickly it can change. Thanks.
