### ISSUE TITLE
No system tray icon after installing optimus-manager-qt

### ISSUE THREAD

**Issue by OmerBit** [Shatur/optimus-manager-qt#29]
Hello so i have installed optimus-manager and its working very good!!, I'm using GDM and Gnome.
But one thing not have working is the tray icon, I tried to find in the settings maybe i need to enable it but could not find anything there.
Please have a look maybe need to update the package?
My laptop model is asus gl753ve
arch linux 5.3.7-arch1-1-ARCH
Thanks!!!

**Comment by Shatur** [comment]
Strange, the application should always show the tray icon. Do you have other Qt applications that works in tray? If not, could you install `qbittorrent` or something with tray icon and check if the tray icon exists for this app?

**Comment by OmerBit** [comment]
> Strange, the application should always show the tray icon. Do you have other Qt applications that works in tray? If not, could you install `qbittorrent` or something with tray icon and check if the tray icon exists for this app?

@Shatur95 

I have pamac updates indicator, Removable drive menu,and Freon.
about qbittorrent there is no tray icon, i got to the settings and tray icon option is unavailable.
in the wiki of that program they said:

> My menu icons in qBittorrent are gone, why?

You are probably using GNOME ≥ 2.28. By default, this window manager is no longer displaying menu icons.
You can change this behavior by issuing the following two commands in a terminal:

 gconftool-2 --type boolean --set /desktop/gnome/interface/buttons_have_icons true
 gconftool-2 --type boolean --set /desktop/gnome/interface/menus_have_icons true

**Comment by Shatur** [comment]
Yes, if you do not see the tray icons from other Qt applications, this is not an Optimus Manager Qt issue :(

> gconftool-2 --type boolean --set /desktop/gnome/interface/buttons_have_icons true
> gconftool-2 --type boolean --set /desktop/gnome/interface/menus_have_icons true

Did these console commands help you?

**Comment by OmerBit** [comment]
No, i think they removed the option from Gnome 3.3X im not sure still trying to read about that.
but for sure i dont see any solution right now, so cant use that tray icon :(

**Comment by Shatur** [comment]
Do you have [KStatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support) extension installed?
Also take a look at [this](https://github.com/inzar98/optimus-manager-argos).

**Comment by OmerBit** [comment]
> Do you have [KStatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support) extension installed?
> Also take a look at [this](https://github.com/inzar98/optimus-manager-argos).

Well its fixed the problem, after the install i did a restart and now i can show tray icons.
but its have shown only after i find the app and open it.
now qbittorrent working too.
thank man!!

**Comment by Shatur** [comment]
> but its have shown only after i find the app and open it.

You can enable autostart in settings.

 > thank man!!

You are welcome :)
