### ISSUE TITLE
Is this "Tripple" a typo?

### ISSUE THREAD

**Issue by Rasphino** [Shatur/optimus-manager-qt#3]
I found this when I am translating...
![image](https://user-images.githubusercontent.com/12711106/55083491-938d8d00-50de-11e9-974f-183d77e90d19.png)

I think this "tripple" should be "triple"?
Here is a [arch wiki entry](https://wiki.archlinux.org/index.php/NVIDIA/Troubleshooting#Avoid_screen_tearing_in_KDE_(KWin)) which use "triple".

**Comment by Shatur** [comment]
Oh, yes, it's a typo.
Can you, please, send PR?

**Comment by Rasphino** [comment]
Sure, my pleasure~

**Comment by Rasphino** [comment]
Btw, I think it is better to use `tr().arg()` instead of string concatenation in [this line](https://github.com/Rasphino/optimus-manager-qt/blob/eff3e4ab7c085159b96906722b03593cc943d9b6/src/appsettings.cpp#L71), since `tr().arg()` enables a more elegant way for i18n.

Can I change this with the typo PR?

**Comment by Shatur** [comment]
Yes, I agree with you. Add to the PR :)
