### ISSUE TITLE
App does not detect available nvidia module

### ISSUE THREAD

**Issue by bonacan** [Shatur/optimus-manager-qt#30]
Hi. So the pop up that says "nvidia module is not available" appears right before the switch even though I have everything installed and the switch itself works properly. I recently switched from LTS kernel to Zen kernel and this didn't happen before on LTS kernel. I have "linux-zen linux-zen-headers dkms nvidia-dkms bbswitch-dkms optimus-manager optimus-manager-qt" installed and they are all at the latest version. Maybe it is because zen doesn't have a specific package of its own for nvidia drivers?

Btw, I am not that much familiar with GitHub and issue reporting so I apologize for that and also my bad English. If there is anything I can do to help like post some command line output I would gladly do so.

Specs:
Arch Linux
i5-8250u
MX150+UHD620
8GB Memory

Thank you and sorry for taking your time

**Comment by Shatur** [comment]
Hello! Thanks, fixed.

**Comment by bonacan** [comment]
Yep it works now, thank you :)
