### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by indarianne** [Shatur/optimus-manager-qt#32]
**Describe the bug**
Unfortunately all icons in the application and tray are missing. At the same time other qt applications have icons (i.e. Telegram, qBittorrent). 

**Screenshots**
![tray-icons](https://user-images.githubusercontent.com/13622133/69913128-0bf9da00-1434-11ea-8d47-0fecdc53e41c.png)
![app-icons](https://user-images.githubusercontent.com/13622133/69913183-bf62ce80-1434-11ea-956e-e22028dda8be.png)

**Environment (please complete the following information):**

-   OS: Arch Linux
-   Desktop environment: XFCE4
-   Optimus Manager version: 1.2.2
-   Optimus Manager Qt version: 1.4.2

P.S. I use papirus-dark-theme of icons, if it is relevant info for investigation.

**Comment by Shatur** [comment]
Thanks for the issue. Could you install `qt5-styleplugins` (if missing) and try to run the app with `env QT_STYLE_OVERRIDE=gtk2 optimus-manager-qt` (you also need to close the previous instance).

**Comment by indarianne** [comment]
Hm, it seems it fixed itself somehow. I am not sure of what could it be, but I cannot reproduce it anymore and have icons... If I will reproduce it, I will report to you more. Sorry for disturbing :)

**Comment by indarianne** [comment]
One possible reason - could it be qt5-svg? It was the dependency in qBittorrent and I think it fixed itself after I installed this client. I believe it is not listed as dependency in your app.

**Comment by Shatur** [comment]
Hm... Could you check it, please? I use KDE and have a lot of apps that uses `qt5-svg`, so I can't delete it for checking :)

**Comment by indarianne** [comment]
Yes, can confirm. After deletion of qt5-svg icons issue reappears. :)

**Comment by Shatur** [comment]
Thanks, added `qt5-svg` as a dependency!
