### ISSUE TITLE
Do not initialize as regular user

### ISSUE THREAD

**Issue by markeenmelo** [Shatur/optimus-manager-qt#34]
I'm using Arch Linux and aur/optimus-manager-qt on a Plasma including kde-applications DE nearly installed and optimus-manager is not opening as a user. It only works when I run it as sudo.

It works if I keep _plasma=false.

**Comment by Shatur** [comment]
I can't reproduce the issue. Do you can run `optimus-manager` itself? What does it print if you run the GUI from terminal?

**Comment by markeenmelo** [comment]
Yes, I can use optimus-manager to switch between the graphic cards.
optimus-manager --status output:
Optimus Manager (Client) version 1.2.2

Current GPU mode : nvidia
GPU mode requested for next login : nvidia
GPU mode for next startup : nvidia
Temporary config path: no

When I type optimus-manager-qt on my terminal I get stuck and no output until I press Ctrl C.

**Comment by markeenmelo** [comment]
If I do sudo optimus-manager-qt I get this:
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QSystemTrayIcon::setVisible: No Icon set

**Comment by Shatur** [comment]
What version of the GUI are you using? I made a template for filling issues for a reason!

**Comment by markeenmelo** [comment]
Plasma:  5.17.4-1
optimus-manager: 1.2.2-2
optimus-manager-qt: 1.4.4-1

**Comment by Shatur** [comment]
What do you see when starting from sudo? Can you send a screenshot?

**Comment by markeenmelo** [comment]
![Screenshot_20191227_122919](https://user-images.githubusercontent.com/8158196/71522778-e205cd00-28a4-11ea-9865-3a5f68a80c55.png)

**Comment by Shatur** [comment]
It is very strange. Are you sure that when starting from a regular user nothing appears in the tray? Have you checked the entire system tray?

**Comment by markeenmelo** [comment]
Ok, the problem is that it was hidden on my system tray. Can I ask what are the differences in setting _plasma to true?

**Comment by Shatur** [comment]
With this flag the app uses Plasma system tray API. For example, you will see extended tooltip.

**Comment by markeenmelo** [comment]
Ok, thank you.
