### ISSUE TITLE
Icon Fails to Switch With Optimus Mode

### ISSUE THREAD

**Issue by MegaShinySnivy** [Shatur/optimus-manager-qt#37]
**Bug description** Failure to change icon in system tray
Steps to reproduce:
    1. Open optimus-manager-qt via left click.
    2. Change to anything but Intel iGPU
    3. The icon still shows the Intel iGPU in the system tray after a logout/login
**Expected behavior** The icon shifting to either Hybrid or NVidia
Screenshots If applicable, add screenshots to help explain your problem.
**Environment**
    • OS: Manjaro stable
    • Desktop environment: KDE
    • Optimus Manager version: (1.2.22) 
    • Optimus Manager Qt version: (1.4.5) 
**Additional context** This happened after a recent update. No errors are reported, and I think the switch is working. Either that, or my iGPU is a beast.

**Comment by Shatur** [comment]
Hi! Could you show me the output from `optimus-manager --print-mode` after switching?

**Comment by MegaShinySnivy** [comment]
``current GPU mode: intel``
Turns out I was wrong. Is this a bigger issue then?

**Comment by Shatur** [comment]
Unfortunately yes. For some reason, you cannot switch GPU. Read about possible solutions [here](https://github.com/Askannz/optimus-manager).
This repository is only for GUI.
