### ISSUE TITLE
建议在AUR包中添加`qt5-svg`依赖关系解决图标问题

### ISSUE THREAD

**Issue by eonun** [Shatur/optimus-manager-qt#38]
建议添加一个依赖关系来解决`QSystemTrayIcon::setVisible: No Icon set`图标设置失败的问题
依赖包：`extra/qt5-svg`

**Comment by Shatur** [comment]
I don’t understand Chinese, but if my translator translated correctly, then you say that the package in AUR has missing `qt5-svg` dependency. Added.

**Comment by eonun** [comment]
Right, add the `qt5-svg` dependency to fix the icon not showing
对，添加`qt5-svg`依赖关系，解决图标不显示的问题
