### ISSUE TITLE
Can't install the latest version (1.5.1) on Manjaro

### ISSUE THREAD

**Issue by rejuvenator** [Shatur/optimus-manager-qt#50]
**Bug description**
When I try to update to the latest version via AUR, I get the message

> could not satisfy dependencies:
> - unable to satisfy dependency 'optimus-manager>=1.3' required by optimus-manager-qt

**Steps to reproduce**
1. Open Pamac
2. Go to Updates
3. Hit "Apply"
4. Message pops up.

**Expected behavior**
Application being updated.

**Environment**

-   OS: Manjaro
-   Desktop environment: KDE
-   Optimus Manager version: (e.g. 1.3-1)
-   Optimus Manager Qt version: current: 1.5.0-1, target: 1.5.1-1

**Comment by Shatur** [comment]
It looks like you need to clear cache. I tested it just now with `yay` and it works as expected.

**Comment by Shatur** [comment]
I assume that the issue can be closed.
