### ISSUE TITLE
Generated config file and autostart script filename are badly encoded 

### ISSUE THREAD

**Issue by nikitautiu** [Shatur/optimus-manager-qt#55]
## Bug description
The config file generated at `/etc/optimus-manager/optimus-manager.conf` is badly encoded. Basically looks like this:

```
[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
ignore_abi=no
modeset=yes
options=overclocking

[optimus]
%23%20%20%20%20%20%20%20%20%20Also%2C%20it%20will%20perform%20a%20PCI%20remove%20even%20if%20pci_remove=no.
%23%20GPU%20mode%20to%20select%20when%20startup_mode=auto and the computer is running on external power.
%23%20Ignored%20if%20switching="nouveau or switching=bbswitch."
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=intel
startup_auto_extpower_mode=hybrid
startup_mode=auto
switching=bbswitch
```

The name of the `.desktop` file generated in `~/.config/autostart` was as also badly encoded.

## Steps to reproduce

1.  Go to settings and set config file type to "Permanent"
2. Enable "Launch at startup"
2.  Modify some settings and save them
3. Check the output

## Environment

-   OS: Arch Linux
-   Desktop environment: Gnome
-   Optimus Manager version: 1.3
-   Optimus Manager Qt version: 1.5.1

**Comment by Shatur** [comment]
Can't reproduce. Could you provide a screenshot with the settings on the Optimus tab which are produce this output?

And could you also send autostart file?

**Comment by nikitautiu** [comment]
Sure. This is the content of the autostart file (the content doesn't seem bad, just the filename):

```
[Desktop Entry]
Name=Optimus Manager
Name[zh_CN]=Optimus 管理器
Comment=A program to handle GPU switching on Optimus laptops
Comment[ru]=Программа для управления переключением графических процессоров на ноутбуках c Optimus
Comment[zh_CN]=处理双显卡笔记本电脑 GPU 切换的程序
Keywords=nvidia;optimus;settings;switch;GPU;
Keywords[ru]=nvidia;optimus;settings;switch;GPU;настройки;видеокарта;
Exec=optimus-manager-qt
Icon=optimus-manager-qt
Terminal=false
StartupNotify=false
Type=Application
Categories=System;Settings;Qt
```

I attached screenshots of all the settings. 

![Screenshot from 2020-06-23 13-07-07](https://user-images.githubusercontent.com/581329/85391517-f45e7c00-b552-11ea-8f33-1c3c1301ff73.png)
![Screenshot from 2020-06-23 13-08-22](https://user-images.githubusercontent.com/581329/85391509-f1638b80-b552-11ea-83f7-2b8d0f65030f.png)
![Screenshot from 2020-06-23 13-08-05](https://user-images.githubusercontent.com/581329/85391513-f32d4f00-b552-11ea-902a-e904414b9a4b.png)
![Screenshot from 2020-06-23 13-07-54](https://user-images.githubusercontent.com/581329/85391515-f32d4f00-b552-11ea-83e5-79663a871eda.png)
![Screenshot from 2020-06-23 13-07-40](https://user-images.githubusercontent.com/581329/85391516-f3c5e580-b552-11ea-96fc-a9977fdc67ba.png)
![Screenshot from 2020-06-23 13-05-59](https://user-images.githubusercontent.com/581329/85391520-f45e7c00-b552-11ea-93e7-a95479fc6134.png)

**Comment by Shatur** [comment]
I fixed autostart path issue, but still can't reproduce configuration issue. Could you try to clean configuration and try to reproduce confuguration issue again with exact steps to reproduce?

**Comment by nikitautiu-rist** [comment]
> I fixed autostart path issue, but still can't reproduce configuration issue. Could you try to clean configuration and try to reproduce confuguration issue again with exact steps to reproduce?

Ok, I removed the existing `/etc/optimus-manager/optimus-manager.conf` and the new generated one is clean:

```
[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
ignore_abi=no
modeset=yes
options=overclocking

[optimus]
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=intel
startup_auto_extpower_mode=nvidia
startup_mode=auto
switching=bbswitch
```

I assume the issue was because I had a previous config before where the comment probably came from. 

Thanks for the help!

**Comment by Shatur** [comment]
Nice to see. Please let me know if the issue will be reproduced again.
