### ISSUE TITLE
Setting DPI to zero results in `DPI=@Invalid()`

### ISSUE THREAD

**Issue by dgaus** [Shatur/optimus-manager-qt#57]
**Bug description**
I noticed `optimus-manager --status` was complaining about an invalid DPI setting, so I checked `/etc/optimus-manager/optimus-manager.conf` and found
```
DPI=@Invalid()
```
Setting it to a number works normally.

**Environment**

-   OS: Arch Linux
-   Desktop environment: Plasma
-   Optimus Manager version: 1.3
-   Optimus Manager Qt version: 1.5.2

Thanks

**Comment by Shatur** [comment]
How do you reproduced it?
I tried to play with this value in GUI and always have a number in this field.

**Comment by dgaus** [comment]
That is odd. For me I just open the settings and set the DPI to 0. Maybe a difference in QT or a related library? My Arch installation is up to date.

Set to 192 and click OK
```
$ grep DPI optimus-manager.conf
DPI=192
```
Set to 0 and click OK
```
$ grep DPI optimus-manager.conf
DPI=@Invalid()
```

**Comment by Shatur** [comment]
Thank you! Reproduced and fixed.

**Comment by Shatur** [comment]
Could you try the latest master? There is `optimus-manager-qt-git` package in AUR.

**Comment by dgaus** [comment]
Latest removes the DPI key if set to 0, thanks

**Comment by Shatur** [comment]
Yes, I think this is how it should work according to the comments in the configuration.

**Comment by dgaus** [comment]
Hm one bug however. When restarting optimus-manager-qt it sets the DPI to 96 internally if it doesn't find the DPI key

**Comment by dgaus** [comment]
Also I just noticed if I untick `overclocking options` I get `options=@Invalid()` in my optimus-manager.conf

**Comment by dgaus** [comment]
I think it's valid to leave options empty like this `DPI=`

**Comment by Shatur** [comment]
Thanks, fixed both issues.
