### ISSUE TITLE
Switching from Intel to Nvidia renders black screen instead of login screen (KDE Plasma)

### ISSUE THREAD

**Issue by Socterean** [Shatur/optimus-manager-qt#6]
As stated in the title, when I switch to Nvidia using `optimus-manager-qt` instead of a login screen the screen remains black. Inserting the user `password` and hitting `enter` logs me in, but is annoying if I misspell my password because I need to blindly delete it and reinsert it.

I want to mention also that I have replaced `PLASMA=false` with `PLASMA=true` in PKGBUILD before building `optimus-manager-qt`.

Thank you!

OS: Manjaro Linux x86_64
Host: 20217 Lenovo IdeaPad Y510P
Kernel: 5.0.5-1-MANJARO
Resolution: 1920x1080
DE: KDE 5.15.3-1
CPU: Intel i7-4700MQ (8) @ 3.400GHz
GPU: Intel 4th Gen Core Processor
GPU: NVIDIA GeForce GT 750M
Memory: 1958MiB / 7892MiB

**Comment by Shatur** [comment]
This program is only a graphical interface for `optimus-manager`. As mentioned in the [readme](https://github.com/Shatur95/optimus-manager-qt#optimus-manager-qt), report all non-interface related issues in [this](https://github.com/Askannz/optimus-manager) repository.

**Comment by Socterean** [comment]
I know, but this only happens when using the system tray to switch cards, it doesn't happen when using the other deprecated system tray or when switching from the terminal, so I believed that it must be something with how this program handles things.

Also, disabling card switch confirmation doesn't work and setting the DPI doesn't either.

**Comment by Shatur** [comment]
Oh, okay, sorry. I'll look into it, thank you!

**Comment by Shatur** [comment]
I just checked the DPI setting, the value in the configuration file is set correctly. I guess the DPI issue is in `optimus-manager`.

About the black screen: it's really strange, that the problem only appears when using `optimus-manager-qt` since the program just send videocard name for switching (`intel` or `nvidia`) to the `optimus-manager` daemon. All video switching occurs on the `optimus-manager` side. Maybe the problem happens sometimes? Could you check it again?

**Comment by Socterean** [comment]
No problem, I should have mentioned this in the first place.

Also I think I know why setting the DPI doesn't work. In `optimussettings.cpp` the `m_settings` variable makes changes to `optimus-manager.conf`, but to change the DPI the DPI settings should be made in `/etc/optimus-manager/xorg-nvidia.conf` or the change would not work, and after that the sistem must be **rebooted**.

I had a somewhat related issue when switching to Nvidia with the text being small because of the DPI as it can be seen [here](https://github.com/Askannz/optimus-manager/issues/67).

And to fix that issue I had to add two lines in `/etc/optimus-manager/xorg-nvidia.conf` :

```
Option "UseEdidDpi" "FALSE"
Option "DPI" "96 x 96"
```

At first I too added them in `optimus-manager.conf` but that didn't worked.

Also if we are here, couldn't those two lines be added by default by `optimus-manager-qt` when `PLASMA=true` as a way to mitigate that problem for many more users?!

**Comment by Shatur** [comment]
> to change the DPI the DPI settings should be made in `/etc/optimus-manager/xorg-nvidia.conf`

`optimus-manager.conf` have a special setting for this. And it's change DPI through `xrandr`. `optimus-manager-qt` simple changes this setting. Maybe author of the `optimus-manager` will rework this option. All changes in `/etc/optimus-manager/xorg-nvidia.conf` need to be done manually.

> Also if we are here, couldn't those two lines be added by default by optimus-manager-qt when PLASMA=true as a way to mitigate that problem for many more users?!

I using this program with PLASMA=true (and with KDE with SDDM), but I don't have this issue.
It looks like you have hardware-specific issue.

**Comment by Socterean** [comment]
Sorry for getting back so late. But unfortunately I haven't had spare time to properly test it until now. I have tried again switching the version 0.7.1 to 0.8.2, and oddly enough this time on 0.8.2 the problem persists when trying all the available options to switch the graphics card (terminal, old deprecated tray, new tray indicator).

So I believe that indeed the problem lies somewhere in `optimus-manager` itself.

I am sorry for the false lead and I believe that the topic can be closed now.

Thank you for your help!
