### ISSUE TITLE
Unable to detect AMD iGPU

### ISSUE THREAD

**Issue by hexadecimalDinosaur** [Shatur/optimus-manager-qt#61]
**Bug description**
If installed on a system with an AMD iGPU and Nvidia dGPU running `optimus-manager-amd-git` from the AUR, the AMD iGPU is not detected an causes a crash

**Steps to reproduce**

1.  Use laptop with AMD iGPU (eg Zephyrus G14)
2.  Install `optimus-manager-amd-git` from AUR
3.  Start and enable `optimus-manager` using `systemctl`
4.  Install `optimus-manager-qt-git` from AUR
5.  Start `optimus-manager-qt`

**Expected behavior**
Detect AMD as an iGPU and offer options to switch between AMD iGPU and Nvidia GPU

**Environment**

-   OS: Arch Linux
-   Desktop environment: i3-gaps
-   Optimus Manager version: 1.2.2 amd_support branch
-   Optimus Manager Qt version: 1.5.3.r6.geb92a21-1

**Additional context**
```
$ optimus-manager-qt --version
Unable to detect GPU
[1]    246781 abort (core dumped)  optimus-manager-qt --version

$ optimus-manager --print-mode

Current GPU mode : amd
```

**Comment by Shatur** [comment]
Optimus Manager does not support AMD officially. When [this](https://github.com/Askannz/optimus-manager/pull/268) PR will be merged I will add support for it in GUI.

**Comment by dphaldes** [comment]
I am using my [own fork](https://github.com/luiq54/optimus-manager/tree/amd_support_fix) of Optimus manager based on the `amd_support` branch on master. Is there a way to use the applet by making small changes till support is added for it officially ?
(C++ + Qt isn't my strong suite)

**Comment by Shatur** [comment]
Yes, it's possible, but I currently on vacation and I probably need help because I do not have such hardware.

**Comment by dphaldes** [comment]
I am sorry to interrupt your vacation. I will wait for the official support. Also please do tell if you need some hardware testing. I will be more than glad to help!

**Comment by Shatur** [comment]
No problem, I always reply to messages :)
Okay. Currently you can provide a feedback to that PR with AMD support to let author know that it works correctly.

**Comment by Ann1kaB** [comment]
@Shatur95 I actually have a fork of your GUI front end with experimental AMD support found [here](https://github.com/Hyper-KVM/optimus-manager-qt/tree/amd-support)

**Comment by Shatur** [comment]
Awesome! Feel free to send a PR. I will leave a review and will merge it as soon as your AMD branch is merged with Optimus Manager master.

**Comment by dphaldes** [comment]
@Hyper-KVM Does it work with any version of Optimus Manager? I am using a modified version of the `amd_support` branch (I have only altered the amd_hybrid configuration in `xorg.py`)

**Comment by hexadecimalDinosaur** [comment]
@luiq54 I don't think so because looking through the diff of his fork, it looks like he just went through and replaced `intel` everywhere with `integrated` like they propose in the https://github.com/Askannz/optimus-manager/pull/268. `amd_support` uses `amd` not `integrated` so it wont work.

**Comment by Shatur** [comment]
@UserBlackBox, it looks like daemon commands not changed, so it could work.

**Comment by dphaldes** [comment]
@UserBlackBox I don't know which version you are using, but my version does use `integrated` instead of `amd`.

**Comment by dphaldes** [comment]
@Hyper-KVM I wanted to test out your fork to see if it works or not but I am unable to build the app(KF5 error) but this version builds/runs fine. Do you happen to know the issue ?

```
CMake Error at CMakeLists.txt:25 (find_package):
  By not providing "FindKF5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "KF5", but
  CMake did not find one.

  Could not find a package configuration file provided by "KF5" with any of
  the following names:

    KF5Config.cmake
    kf5-config.cmake
```
(I have ecm installed )

**Comment by Shatur** [comment]
@luiq54, the error says that you missing `extra-cmake-modules`. Are you sure that you have it installed? Fork do not have any changes in CMakeLists.txt. You can simply install it by just editing PKGBUILD from AUR (just change repo to the fork).

**Comment by dphaldes** [comment]
I do have `extra-cmake-modules` installed. As I said, the original branch builds and runs fine. I only had difficulties building the fork. I reinstalled ecm and kf5 frameworks but it still errors out. I will try the PKGBUILD method.

Edit: I tried the AUR it worked just fine. So it must have been a mistake from my side

**Comment by Shatur** [comment]
Try `optimus-manager-qt-git` with `optimus-manager-git`, it should work now.

**Comment by nklyshko** [comment]
I have installed latest optimus-manager-git and optimus-manger-qt-git, but in notification area I see "Intel" icon instead of AMD. And in context menu, item "Switch to Integrated" have not any icon.

**Comment by Shatur** [comment]
> I have installed latest optimus-manager-git and optimus-manger-qt-git, but in notification area I see "Intel" icon instead of AMD. 

Do you see the Intel icon in Integrated or Hybrid mode? Could you provide `glxinfo` output (it will be big, please upload it somewhere).

> And in context menu, item "Switch to Integrated" have not any icon.

This is okay. I removed icon for this item because I can't display proper icon when you on Nvidia GPU (integrated card type will be unavailable).

**Comment by nklyshko** [comment]
I see Intel icon in Integrated mode.
My glxinfo command is broken for some unknown reason - It prints something strange (many lines like this `0x531 32 tc  0  32  0 r  y .   8  8  8  8 .  s  0 24  8  0  0  0  0  0 0 None`). 
This is my inxi -F output:
```System:    Host: nikita-asus-fx505du Kernel: 5.7.19-2-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.19.5 Distro: Manjaro Linux 
Machine:   Type: Laptop System: ASUSTeK product: TUF Gaming FX505DU_FX505DU v: 1.0 serial: <superuser/root required> 
           Mobo: ASUSTeK model: FX505DU v: 1.0 serial: <superuser/root required> UEFI: American Megatrends v: FX505DU.306 
           date: 07/12/2019 
Battery:   ID-1: BAT0 charge: 31.8 Wh condition: 31.8/48.1 Wh (66%) 
CPU:       Topology: Quad Core model: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx bits: 64 type: MT MCP L2 cache: 2048 KiB 
           Speed: 2926 MHz min/max: 1400/2300 MHz Core speeds (MHz): 1: 2917 2: 2901 3: 1177 4: 1177 5: 2934 6: 2942 7: 1176 
           8: 1177 
Graphics:  Device-1: NVIDIA TU116M [GeForce GTX 1660 Ti Mobile] driver: nvidia v: 455.28 
           Device-2: Advanced Micro Devices [AMD/ATI] Picasso driver: amdgpu v: kernel 
           Device-3: IMC Networks USB2.0 HD UVC WebCam type: USB driver: uvcvideo 
           Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: amdgpu resolution: 1920x1080~120Hz 
           OpenGL: renderer: AMD RAVEN (DRM 3.37.0 5.7.19-2-MANJARO LLVM 10.0.1) v: 4.6 Mesa 20.1.8 
Audio:     Device-1: Advanced Micro Devices [AMD] Family 17h HD Audio driver: snd_hda_intel 
           Sound Server: ALSA v: k5.7.19-2-MANJARO 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           IF: enp2s0 state: up speed: 100 Mbps duplex: full mac: 04:d4:c4:e8:0a:77 
           Device-2: Realtek RTL8822CE 802.11ac PCIe Wireless Network Adapter driver: rtw_pci 
           IF: wlp4s0 state: up mac: 80:91:33:f4:be:91 
           IF-ID-1: br-33ed5b778008 state: down mac: 02:42:d9:c9:2c:d8 
           IF-ID-2: br-53ded262b990 state: down mac: 02:42:fc:80:f7:c0 
           IF-ID-3: docker0 state: down mac: 02:42:e5:cc:d3:23 
           IF-ID-4: vboxnet0 state: up speed: 10 Mbps duplex: full mac: 0a:00:27:00:00:00 
Drives:    Local Storage: total: 1.38 TiB used: 334.88 GiB (23.8%) 
           ID-1: /dev/nvme0n1 vendor: Micron model: 2200V MTFDHBA512TCK size: 476.94 GiB 
           ID-2: /dev/sda vendor: Samsung model: SSD 860 EVO 1TB size: 931.51 GiB 
Partition: ID-1: / size: 451.37 GiB used: 184.00 GiB (40.8%) fs: ext4 dev: /dev/nvme0n1p2 
Swap:      ID-1: swap-1 type: partition size: 17.06 GiB used: 15.4 MiB (0.1%) dev: /dev/nvme0n1p3 
Sensors:   System Temperatures: cpu: 56.8 C mobo: N/A gpu: amdgpu temp: 56 C 
           Fan Speeds (RPM): cpu: 2700 
Info:      Processes: 319 Uptime: 3h 34m Memory: 15.14 GiB used: 12.42 GiB (82.1%) Shell: Bash inxi: 3.1.05 
```

**Comment by Shatur** [comment]
>  My glxinfo command is broken for some unknown reason - It prints something strange (many lines like this 0x531 32 tc 0 32 0 r y . 8 8 8 8 . s 0 24 8 0 0 0 0 0 0 None).

No, no, it's okay. Just send me the entire file with its output. I just need to get a provider name.

**Comment by nklyshko** [comment]
This is entire output file.
[glxinfo.txt](https://github.com/Shatur95/optimus-manager-qt/files/5474111/glxinfo.txt)

**Comment by Shatur** [comment]
Do you use AMD with `modesetting` driver?

**Comment by nklyshko** [comment]
Yes.

**Comment by Shatur** [comment]
@CraftCoderr, could you help me with debugging? I need you to install QtCreator and launch app in debug mode.

**Comment by nklyshko** [comment]
I suggested you need this:
![image](https://user-images.githubusercontent.com/7105938/97879321-e86c9d00-1d30-11eb-9526-86bc5e4c0005.png)

It seems that we can't determine gpu vendor when modesetting is used.

**Comment by Shatur** [comment]
Thank you a lot! It seems that we need to use another mechanism when `modesetting` is used.

**Comment by Shatur** [comment]
@CraftCoderr, should be fixed by b5bda42f7b0212a06038a7063158cb66344b619d, could you check again?

**Comment by nklyshko** [comment]
It's not working for me, because cpuInfo.atEnd() always return true. I have tried to debug this and found that in Qt docs:
```
bool QFileDevice::atEnd() const
Reimplements: QIODevice::atEnd() const.

Returns true if the end of the file has been reached; otherwise returns false.

For regular empty files on Unix (e.g. those in /proc), this function returns true, since the file system reports that the size of such a file is 0. Therefore, you should not depend on atEnd() when reading data from such a file, but rather call read() until no more data can be read.
```

**Comment by Shatur** [comment]
@CraftCoderr, good catch!
Should be fixed by b7351a6f5a956dd8f07b31d53b11bebbaa73888b.

**Comment by nklyshko** [comment]
It works if I changing `endsWith` to `contains`, because line contains trailing `\n`.

**Comment by Shatur** [comment]
Thanks! Will it work if use `endsWith` with `\n` in the end? The `cointains` function will just check for every character from the beginning.

**Comment by nklyshko** [comment]
Yes, it will work, tested.

**Comment by Shatur** [comment]
Thank you a lot for the feedback. Just pushed the fix.
Do other AMD-related features work?

**Comment by dphaldes** [comment]
I reinstalled it today and so far it has worked without any issues. I made a [similar comment](https://github.com/Askannz/optimus-manager/issues/109#issuecomment-723416014) in optimus-manager too.
Thanks !

**Comment by Shatur** [comment]
Thanks! Feel free to open a new issue if you find something.
