### ISSUE TITLE
Unable to create autorun file

### ISSUE THREAD

**Issue by AchmadFathoni** [Shatur/optimus-manager-qt#65]
**Bug description**
`"Unable to create autorun file from '/usr/share/applications/io.optimus_manager.OptimusManagerQt.desktop'"`

**Steps to reproduce**
1. Run `optimus-manager-qt` from terminal
2. Right click icon tray and choose settings
3. Check Launch at startup
4. Click ok

**Expected behavior**
Software save configuration state and make manager auto start.

**Environment**

-   EndeavourOS
-   KDE
-   Optimus Manager 1.3
-   Optimus Manager Qt  1.5.2

**Additional context**
even with `sudo` error still occurs. _plasma=true in PKGBUILDS

**Comment by Shatur** [comment]
Hm... Can't reproduce it on my machine. Could you try on the latest master?

**Comment by AchmadFathoni** [comment]
> Hm... Can't reproduce it on my machine. Could you try on the latest master?

I am using git version from AUR
```
pkgname=optimus-manager-qt-git
pkgver=1.5.3.r10.ge0f46ab
```
Still the same.

**Comment by Shatur** [comment]
Could you check if `/usr/share/applications/io.optimus_manager.OptimusManagerQt.desktop` and `~/.config/autostart` exists?

**Comment by AchmadFathoni** [comment]
```
[toni@AN515 ~]$ ls /usr/share/applications/io.optimus_manager.OptimusManagerQt.desktop -la
-rw-r--r-- 1 root root 625 Sep  5 22:55 /usr/share/applications/io.optimus_manager.OptimusManagerQt.desktop
[toni@AN515 ~]$ ls ~/.config/autostart -la
ls: cannot access '/home/toni/.config/autostart': No such file or directory

```

**Comment by Shatur** [comment]
Oh, got it! Just create `/home/toni/.config/autostart` folder to solve your issue.
From my side I will add a check for it in the app.
