### ISSUE TITLE
System tray doesn't show optimus-manager-qt after upgrading qt to 5.15.1

### ISSUE THREAD

**Issue by chebro** [Shatur/optimus-manager-qt#71]
**Bug description**
This is exactly like #29. I don't see the tray icon. It was working until yesterday, but it doesn't show anymore.

**Screenshots**
![optimus-manager-qt-issue](https://user-images.githubusercontent.com/54331348/94924162-a7d3f680-04da-11eb-8c72-c7d8ff32cca4.png)

**What I've tried already**
- As requested in issue #29, I tried installing `qbittorrent`, and I can see the icon as seen in the screenshot above. 
- I have KStatusNotifierItem/AppIndicator installed and enabled. 
- Uninstalled and reinstalled the `optimus-manager-qt` package.
- Several reboots.

**Environment**

-   Distro: Manjaro Linux
-   Desktop: GNOME 3.36.6 tk: GTK 3.24.23 wm: gnome-shell dm: GDM 3.36.3
-   Optimus Manager version: 1.3.1-1
-   Optimus Manager Qt version: 1.5.3-1

**Additional context**
I'm not entirely sure, but I think this started happening after performing a full system upgrade using `sudo pacman -Syu` to install the latest Manjaro update.

**Comment by Shatur** [comment]
Did you build a project with `_plasma = true` in a PKGBUILD?

**Comment by chebro** [comment]
> Did you build a project with `_plasma = true` in a PKGBUILD?

I don't recall building anything explicitly with that flag. 

Also, optimus-manager works from the command line.

**Comment by Shatur** [comment]
Could you try to build it manually?

```bash
git clone https://aur.archlinux.org/optimus-manager-qt.git
cd optimus-manager-qt
makepkg -si
```

**Comment by chebro** [comment]
> Could you try to build it manually?

Same. It didn't work :(

**Comment by Shatur** [comment]
Hm... Could download the github repo and try to open in QtCreator (or any other IDE). build and run in Debug mode? I just can't reproduce it on my side :(

```bash
git clone --recursive https://github.com/Shatur95/optimus-manager-qt.git
```

**Comment by chebro** [comment]
I've never used qt before, but I tried opening `src/settingsdialoug.ui` and this is what I get:

![omqt](https://user-images.githubusercontent.com/54331348/94933946-b32e1e80-04e8-11eb-9f33-67f3109647ba.png)

How do I build it? 😅

**Comment by Shatur** [comment]
No, no, this is Qt Designer. It just lets you edit .ui files.
I'm talking about Qt Creator (`qrcreator` package).

**Comment by chebro** [comment]
> I'm talking about Qt Creator (`qrcreator` package).

Oh okay, will try doing that.

**Comment by chebro** [comment]
I just checked the Manjaro update [release notes](https://forum.manjaro.org/t/stable-update-2020-10-01-kernels-mesa-kde-framework-deepin-systemd-pamac-xorg-server-qt/29141), and noticed this:

"Qt5 got updated to 5.15.1 16 which might break some"

Do you think this is might be the cause?

**Comment by Shatur** [comment]
I can't say for sure. I use KDE plasma on Arch Linux and everything works. Gnome do not have official system tray icon support (only via third-party extension), so it can be broken. However, you have working qBittorrent. This is very strange.

**Comment by chebro** [comment]
I've just downloaded Qtcreator. And tried running `optimus-manager-qt/src/third-party/singleapplication/examples/build-basic-Desktop-Debug/basic` and attaching a debugger to it, but I'm getting this error:

![debugger](https://user-images.githubusercontent.com/54331348/94942357-ce525b80-04f3-11eb-8485-3656baf7649d.png)

Sorry for the late reply(slow internet speeds today).

**Comment by Shatur** [comment]
Open QtCreator, then click on `File->Open File or Project`, then navigate to the downloaded repo (make sure that you cloned it with `--recursive`) and open `CMakeLists.txt`, then push the `Configure` button. You should have opened project. And then press `F5` to build, launch debugging.

**Comment by chebro** [comment]
![qt](https://user-images.githubusercontent.com/54331348/94949506-a61c2a00-04fe-11eb-93fe-e6ca12faa011.png)

I'm getting this error

**Comment by Shatur** [comment]
Interesting, it looks like we have a crash. Could you send me the full window screenshot?

**Comment by sravanth-chebrolu** [comment]
![Uploading qt1.png…]()
There you go

**Comment by chebro** [comment]
![qt1](https://user-images.githubusercontent.com/54331348/94949812-2e9aca80-04ff-11eb-8784-400142cbefe2.png)
There you go

**Comment by Shatur** [comment]
Thanks! Unfortunately, something wrong with your environment. The application crashes just at startup :( There is nothing to do with the application.
You can try to downgrade Qt or Gnome - there is good [downgrade](https://aur.archlinux.org/packages/downgrade) utility in AUR.

**Comment by chebro** [comment]
> You can try to downgrade Qt or Gnome 

I see, which version would you recommend I downgrade Qt to?

**Comment by Shatur** [comment]
Just open `/var/log/pacman.log`. You will see all recent pacman operations. Try do make a downgrade some recently updated packages.

**Comment by chebro** [comment]
I've tried downgrading whatever I can, but no avail. I guess I'll just have to wait until it's fixed.. :(

For now I'll stick to the command line, I've found [another extension](https://extensions.gnome.org/extension/2908/optimus-manager-indicator/) that does the job for me (although I cannot set the configs graphically), it works.

Thanks for your patience. I think you can close this issue if you think it's unnecessary.

**Comment by Shatur** [comment]
> I've tried downgrading whatever I can, but no avail. I guess I'll just have to wait until it's fixed.. :(

Bad to hear :(

> For now I'll stick to the command line, I've found another extension that does the job for me (although I cannot set the configs graphically), it works.

Yes, probably better choice for Gnome.

I will keep this issue open until the bug will not be fixed.

**Comment by chebro** [comment]
![qt](https://user-images.githubusercontent.com/54331348/95160609-a21e2f80-07be-11eb-9daf-bb41e3e4e150.png)

It started working today again. Not sure what I did to fix it, it just started working again.

**Comment by Shatur** [comment]
Strange :)
But I'm glad the problem resolved itself.
