### ISSUE TITLE
"custom" switching method saved as "none"

### ISSUE THREAD

**Issue by leledumbo** [Shatur/optimus-manager-qt#73]
**Bug description**
When you select "custom" as a switching method, it actually ends up as "none" in the config file.

**Steps to reproduce**

1.  Right click on tray
2.  Click on Settings
3.  Click on Optimus
4.  Set switching method to Custom
5.  Click OK
6.  Redo step 1-3, you will see switching method is set to None

**Expected behavior**
Switching method saved as "custom".

**Screenshots**

**Environment**

-   OS: Manjaro
-   Desktop environment: KDE
-   Optimus Manager version: 1.3
-   Optimus Manager Qt version: 1.5.3 (but the About page still shows 1.5.2)

**Additional context**
It can also be debugged by watching daemon log of optimus manager. When custom is selected, upon clicking OK this is sent:
```
[intel]\nDRI=3\naccel=\ndriver=modesetting\nmodeset=no\ntearfree=yes\n\n[nvidia]\nDPI=96\nPAT=yes\nallow_external_gpus=no\nignore_abi=yes\nmodeset=yes\noptions=overclocking, triple_buffer\n\n[optimus]\nauto_logout=yes\npci_power_control=yes\npci_remove=yes\npci_reset=no\nstartup_auto_battery_mode=intel\nstartup_auto_extpower_mode=nvidia\nstartup_mode=hybrid\nswitching=\n
```
as you can see, the switching value is empty.

From what I can see, it's due to optimussettings.cpp:31 is missing string mapping for custom. Whereas in optimussettings.cpp:65 it is used to get the key, however since no value exists for custom, it returns the default key, which is none.

**Comment by Shatur** [comment]
Nice catch, thank you!
