### ISSUE TITLE
Can't set startup mode to AMD or integrated

### ISSUE THREAD

**Issue by dphaldes** [Shatur/optimus-manager-qt#75]
**Bug description**
No option for the same in the drop down

**Steps to reproduce**
OptimusManagerQT Settings > Optimus > StartupMode

**Screenshots**
![image](https://user-images.githubusercontent.com/51489635/99884486-92668780-2c54-11eb-8503-13d6ef98c888.png)

**Environment**
Arch Linux KDE (Kernel 5.9.9) 

Just having a common "integrated" option will suffice

**Comment by Shatur** [comment]
Thanks!
