### ISSUE TITLE
GNOME: Application icon disappear after reboot

### ISSUE THREAD

**Issue by ghost** [Shatur/optimus-manager-qt#76]
Hi,

I just installed the optimus-manager-qt and it works quite nicely to switch from my nvidia to my integrated intel graphics. But after i reboot the system the icon disappear from the gnome tool bar. I tried to run it manually from the terminal but i got no output. The service optimus-manager still works fine, the problems seems only in the QT GUI.

I'm on Manjaro 20.2, Gnome 3.38.2, running X11.

The same thing happens with Optimus-manager-qt and optimus-manager-qt-git

![Captura de tela de 2020-12-11 01-27-34](https://user-images.githubusercontent.com/7688496/101862117-63a34900-3b50-11eb-931e-d0521649eb4d.png)

Thanks for this amazing program !

**Comment by Shatur** [comment]
Could you show me `ps -aux | grep optimus-manager-qt`?

**Comment by ghost** [comment]
Sure, here it's

```
~ >>> ps -aux | grep optimus-manager-qt                                        
benjamim    1840  0.1  0.3 681280 54564 ?        Sl   10:49   0:00 optimus-manager-qt
benjamim    3421  0.0  0.0 199032  2340 pts/0    S+   10:51   0:00 grep optimus-manager-qt
~ >>>              
```

**Comment by Shatur** [comment]
So, Optimus Manager Qt is running. I think that the problem is in Gnome and it's compatibility with Qt applications because it does not officially support system tray icons. Sorry, I can't help you here.

**Comment by ghost** [comment]
@Shatur95 i discover that installing a Gnome-shell extension to display tray icons solve the problem. Maybe it can help others... Thanks again

https://extensions.gnome.org/extension/2890/tray-icons-reloaded/

![Captura de tela de 2020-12-11 11-01-42](https://user-images.githubusercontent.com/7688496/101912283-4f873800-3ba0-11eb-8606-44756af4555f.png)

**Comment by Shatur** [comment]
Thanks for the workaround! Pinned.

**Comment by trusktr** [comment]
The optimus-manager-qt icon disappeared for me one day a couple months back. I performed an update of my Manjaro system (both official packages and AUR packages), and that solved the issue for me. The updates got everything working well again.

I had previously updated only official packages and not AUR packages, so probably the issue was that the optimus-manager-qt package was behind (it's an AUR package) and not working well with the latest official packages.
