### ISSUE TITLE
GNOME: Broken icons at startup

### ISSUE THREAD

**Issue by roggif** [Shatur/optimus-manager-qt#77]
**Bug description**

Icons aren't shown properly when the program is launched at startup.

**Screenshots**

![Screenshot from 2020-12-28 19-15-12](https://user-images.githubusercontent.com/40572086/103235333-2dccd580-4942-11eb-8a27-ea0e61c00bd0.png)

**Expected behavior**

![Screenshot from 2020-12-28 19-22-04](https://user-images.githubusercontent.com/40572086/103235325-29082180-4942-11eb-9169-6ed83c3b981e.png)

**Environment**

-   OS: Arch Linux
-   Desktop environment: GNOME
-   Optimus Manager version: 1.3.1.r48.g0aed196-1
-   Optimus Manager Qt version: 1.5.2

**Additional context**

My best guess is that the program is launched before the system can load its icons, in fact I managed to fix the issue by delaying optimus-manager-qt's autostart by 1 second editing the launch command in `.config/autostart/io.optimus_manager.OptimusManagerQt.desktop`:

`Exec=bash -c "sleep 1 && optimus-manager-qt"`

**Comment by Shatur** [comment]
Thanks for the issue! I will pin it to let other users know. But I can't fix it because it is definitely a GNOME issue :(
The program works correctly in other DE's.

**Comment by roggif** [comment]
My idea of a fix -source side- was to have a file written for the sole purpose of being cloned to `.config/autostart`. It would be exactly like `io.optimus_manager.OptimusManagerQt.desktop` with only the `Exec` line edited the way I mentioned previously.

The downside is that everyone would have that delay, but, being of just 1 second, I doubt people would actually notice it.
I'll try to write a pull request, but honestly speaking C++ isn't my cup of tea.

**Comment by Shatur** [comment]
> My idea of a fix -source side- was to have a file written for the sole purpose of being cloned to .config/autostart. It would be exaclt like io.optimus_manager.OptimusManagerQt.desktop with only the Exec line edited the way I mentioned previously.

Sorry, I don't like this idea to have an autostart delay in all other DE's. The correct solution is to fix the problem in GNOME.

**Comment by roggif** [comment]
Fair enough. I'll try to come up with something.
