### ISSUE TITLE
Wrong Icon showed

### ISSUE THREAD

**Issue by michaldybczak** [Shatur/optimus-manager-qt#79]
I updated optimus-manager-qt -git today and got nearly a heart attack, because no matter what I chose, I always landed on hybrid, or so I thought. The problem is, on hybrid multiple monitors won't work. I know, they should work by now, but it's still problematic, and I get black both screens when I enable the secondary screen on hybrid mode.

Anyway, I need my Intel mode for multiple monitors and hybrid mode to play games on Nvidia, which rarely happens, while other monitors I use for work very often. So when I thought that switching isn't happening, I was scared.

Luckily, when I checked:

`optimus-manager --print-mode`

I got:

`Current GPU mode : integrated`

However, I still see a hybrid icon, which caused all the confusion. The issue is not so bad, still, seeing the wrong icon is a big bug for this tool nevertheless.

**Comment by Shatur** [comment]
Could you provide `glxinfo` output (it will be big, please upload it as file)?

**Comment by michaldybczak** [comment]
OK, here it is.

[glxinfo.txt](https://github.com/Shatur95/optimus-manager-qt/files/5766722/glxinfo.txt)

**Comment by Shatur** [comment]
Hm... Could you also provide the following output?
`__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia glxinfo | grep vendor`

**Comment by michaldybczak** [comment]
In Intel mode I get this:

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  39
  Current serial number in output stream:  40
```


That is strange. Switching seems to work, dGPU also works on Steam when needed. So functional it seems to be OK, but something is probably misconfigured on my side.

Manjaro was recently changing driver packages names, so I had to uninstall the old ones and install new ones. Previously we had packages lines for each driver line. I had 455 version. Now I switched to generic named package that provides the latest version, currently, also 455, so the result is the same. MHWD (Manjaro's tool) now correctly recognizes setup. Previously it was broken because of the name change.

If you need specifics, all I did was:

`sudo pacman -Rc nvidia-455xx-utils`

`sudo mhwd -i pci video-hybrid-intel-nvidia-prime`

Then, I went through the usual graphic related configs  (which were recreated) to disable them for optimus-manager,

Many old Manjaro users were in the same spot so when we resolve this issue, it will probably help others who may have the same issue coming from the same circumstances.


EDIT: I was wrong. I looked on the command you gave me and realized, it should be run under hybrid mode. So when I switched, I got:

```
server glx vendor string: NVIDIA Corporation
client glx vendor string: NVIDIA Corporation
OpenGL vendor string: NVIDIA Corporation
```

Or maybe the issue is that it doesn't outputs the correct values for Intel mode, hence it hangs on hybrid icon?

**Comment by Shatur** [comment]
Thanks. So, hybrid mode 100% works, but the icon still wrong?
Are you using the latest `-git` version?

**Comment by michaldybczak** [comment]
I updated git version a few days ago and that is where the issue started. On the old version all was fine, but I can't be 100% sure if the optimus-manager-qt update is at fault because I also did the system update and the drivers change at the same time.

In hybrid mode I get the hybrid icon, so all is OK. The Intel mode is a problematic one, because I also get the hybrid icon then.

How your program detects the mode it's in? Optimus-manager shows the mode correctly, so you must use different detection method.

At this point, I suspect something may be wrong on my side, although when it comes to driver functionality all is well, aside multimonitor setup on hybrid. This fails and presents a black screen on both screens. I'm not sure if that is related. Multi-monitor works on Intel and Nvidia. On 455 drivers it also should work on hybrid, but it fails big time. Before it simply failed to detect the second monitor, now it detects it but when I enable it, no monitor is working. Anyway, just to let you know, so you could have a full picture. It may be completely unrelated to the issue at hand, since hybrid mode gets the correct icon and works correctly (aside multimonitors).

**Comment by Shatur** [comment]
> How your program detects the mode it's in? Optimus-manager shows the mode correctly, so you must use different detection method.

Optimus Manager use third-party programs.
I use system calls to detect mode for speed. Here is the code:
 
 https://github.com/Shatur95/optimus-manager-qt/blob/ea53b8e1559d897d8ac84214053c6125b7b693eb/src/optimusmanager.cpp#L385
 
 > At this point, I suspect something may be wrong on my side,
 
 No, I think that the issue in detection. Are you familiar with debugger? :) I need to debug the detection on your machine.

**Comment by michaldybczak** [comment]
Ah, so I need to compile the app with some flags and have debugging packages?

I'm not overly familiar with it but I hope I can do it if you walk me through it. I believe I already did something similar for another git package in the past.

So what I need is the list of packages and the modified PKGBUILD for optimus-manager-qt. Then some instructions how to get the output.

P.S. I have a day off today, so I can respond quicker and move forward with this.

**Comment by Shatur** [comment]
Yes, it's very easy. Install `qtcreator`, clone the repo manually via `git clone https://github.com/Shatur95/optimus-manager-qt.git` and open `CMakeLists.txt` in QtCreator via `File -> Open File or Project`.

Now just put a breakpoint here (just click on gutter and you will have a red dot - this is a breakpoint):
https://github.com/Shatur95/optimus-manager-qt/blob/ea53b8e1559d897d8ac84214053c6125b7b693eb/src/optimusmanager.cpp#L396
And press F5. The program will be compiled, runned and stopped at this point. You will able to move forward via F10. So, you will can iterate over executed logic. Could you check if this line is executed in Intel mode?
https://github.com/Shatur95/optimus-manager-qt/blob/ea53b8e1559d897d8ac84214053c6125b7b693eb/src/optimusmanager.cpp#L401

**Comment by michaldybczak** [comment]
When opening a file, I get a dialog to choose a template:
Aplication Qt
Aplication Qt Quick
Aplication Qt Quick for python, etc.

![2021-01-06_10-50](https://user-images.githubusercontent.com/10132958/103754722-07c3c700-500d-11eb-8fec-f117e4ed4d10.png)

What option should I choose?

I will probably have further questions. I never worked with anything similar so it's all new to me.

**Comment by Shatur** [comment]
It looks like you pressed `New file or Project`. But you should select `Open file or Project`. This will open file picker.

**Comment by michaldybczak** [comment]
It looks like I need to configure the project first. I'm also not sure what "gutter" is in this context. I tried to click various things to have the code to move to the line 396 but didn't find it. I assume because I haven't configured it yet.

Anyway, after opening the given file I get this:

![2021-01-06_10-59](https://user-images.githubusercontent.com/10132958/103755489-34c4a980-500e-11eb-802c-3b2bb4fbe325.png)

**Comment by Shatur** [comment]
> Anyway, after opening the given file I get this:

Yeah, just click "Configure Project".

**Comment by Shatur** [comment]
Gutter it this:
![изображение](https://user-images.githubusercontent.com/22453358/103756016-6db54c00-5017-11eb-9f5d-b36ca595dd36.png)
Click on the mentioned line from the above and you will have this dot.

**Comment by michaldybczak** [comment]
How do I get to the place with the lines of code? I'm walking around the UI and I can't find it. Sorry, it looks like it's not as easy as you said ;P. Please, be patient with me. I run debguing but had to get out of this, because it was doing something and I didn't know what.
Theming seems to be bad on my side, so I run it with breeze override, but it still looks crappy and hardly readable. I guess I have to change system theming for the time being. This is the first app that looks so bad with this theming.

**Comment by Shatur** [comment]
> How do I get to the place with the lines of code?

Press Ctrl + K, type `optimusmanager.cpp`, then go to line 396.

> Please, be patient with me. I run debguing but had to get out of this, because it was doing something and I didn't know what.

No problem :)

> Theming seems to be bad on my side, so I run it with breeze override, but it still looks crappy and hardly readable. I guess I have to change system theming for the time being. This is the first app that looks so bad with this theming.

Something wrong with your Qt theming. I would suggest to run with `QT_QPA_PLATFORMTHEME=gtk2` environment variable.

**Comment by michaldybczak** [comment]
OK, I changed theming, now it looks OKisch. This app simply doesn't do any dark theme correctly.

OK, I got the proper line of code and have the gutter. Run F5 and then F10 after a while.

I'm not sure what now. I see 401 line but as you said, it will run the code till the gutter point, which is line 396. So what should I been looking at?

**Comment by michaldybczak** [comment]
This is what I'm seeing now:

![Screenshot_20210106_112742](https://user-images.githubusercontent.com/10132958/103758294-4740e200-5012-11eb-8e14-11d204433186.jpeg)

EDIT: I'm doing it in Intel mode. Should I switch? Would the mode change the results of this compilation?

**Comment by Shatur** [comment]
Okay, let's try another way:

0. Stop debugging:
![изображение](https://user-images.githubusercontent.com/22453358/103759028-bc64e500-501b-11eb-95e2-2c8cfb7a3a7e.png)
1. Donwload this patch, unpack it, open terminal in the repo folder and execute `git apply <path to the unpacked patch>`
[print.zip](https://github.com/Shatur95/optimus-manager-qt/files/5775254/print.zip)
2. In QtCreator press `Ctrl + R` - the application will be compiled and run with printing. Just send me the output.

**Comment by michaldybczak** [comment]
OK, this is what I got:

```
11:22:15: Start debugging
&"warning: GDB: Failed to set controlling terminal: Niew\305\202a\305\233ciwy ioctl dla urz\304\205dzenia\n"
11:36:45: Ended debugging

11:39:16: Starting /home/michaldybczak/git/build-optimus-manager-qt-Desktop-Debug/optimus-manager-qt ...
modesetting
modesetting
```

This Niew\305\202a\305\233ciwy ioctl dla urz\304\205dzenia\n is weird. It's as if with the random slashes someone added in Polish "incorrect ctl for the device" or something like that. Maybe iotctl ? It's hard to decifer, but it wouldn't be possible for you anyway.

**Comment by Shatur** [comment]
> OK, this is what I got:

Thanks! I will back in few hours and make a fix. It should be easy.

> This Niew\305\202a\305\233ciwy ioctl dla urz\304\205dzenia\n is weird. It's as if with the random slashes someone added in Polish "incorrect ctl for the device" or something like that. Maybe iotctl ? It's hard to decifer, but it wouldn't be possible for you anyway.

This is unrelated issue in QtCreator itself.

**Comment by kingavatar** [comment]
I am also getting the similar issue as well.
The output of `optimus-manager --print-mode` is `Current GPU mode : nvidia` but i still see hybrid icon.
I suspect the problem is with `providerResources->nproviders` which is printing 2 for me which is being returned as HybridGpu
![image](https://user-images.githubusercontent.com/31726036/103764478-8a667980-5041-11eb-97c4-32277bfbe1d1.png)

**Comment by Shatur** [comment]
Fixed. I also decided not to detect Intel and Amd separately and just use one icon for all integrated cards.

**Comment by michaldybczak** [comment]
Now it shows "integrated" icon regardless of intel or hybrid mode.

Since GPU configuration isn't changed on a whim and is long-lasting, can I set Intel icon to be used for integrated mode?
I don't like the current icon.

EDIT: Looks like we can change the icon. Do you have the old icon so we could download it and use? Thanks.

P.S. That multi-monitor setup issue I talked about earlier turned out to be a kernel or kernel modules bug. I switched to 5.9 and multimonitors work in hybrid mode, just FYI.

**Comment by Shatur** [comment]
> Now it shows "integrated" icon regardless of intel or hybrid mode.

Sorry, I made a small typo. Could you check it again?

> Since GPU configuration isn't changed on a whim and is long-lasting, can I set Intel icon to be used for integrated mode?
I don't like the current icon.

Sure, icons was taken from [this theme](https://github.com/masalla-art/masalla-icon-theme). Usually such icons provided by theme. Also check out this [awesome theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme).

**Comment by michaldybczak** [comment]
Now it works OK :).

However, I don't see the icon you used. Maybe it's there, but it's like a looking for a needle in a haystack. Even name search returned a lot of intel something files and whatever I check, this isn't it. There is only some standard Intel icon, which was used in the past. It was fine, but I got used to this monochromatic one that was in use for some time now.

I browsed your project for this icon and I don't see it, only the old, colorful ones.

P.S. I know papirus theme and I don't like it, or at least not as a whole. Some icons are great, some are ugly. This is why I'm not using it.

**Comment by Shatur** [comment]
> It was fine, but I got used to this monochromatic one that was in use for some time now.

The app only provided colored icons. Probably you are looking for `prime-intel` from your icon theme. Just set this name in the integrated icon field.

**Comment by michaldybczak** [comment]
Yes! That was it! Thanks!
