### ISSUE TITLE
Message on startup: The application is already running (XFCE)

### ISSUE THREAD

**Issue by Zeioth** [Shatur/optimus-manager-qt#8]
Another minor bug:
When the option "launch at startup is enabled", I get the next dialog when I start session
![running](https://user-images.githubusercontent.com/3357792/56457929-dd862d80-6381-11e9-96e4-bd40595835e3.png)
And I think I've found the reason for it. It's creating an entry for both, session:
![1](https://user-images.githubusercontent.com/3357792/56457952-09a1ae80-6382-11e9-9711-42bdeb270f79.png)
And autostart
![2](https://user-images.githubusercontent.com/3357792/56457962-0d353580-6382-11e9-9749-c87be5b6752f.png)
Removing one of the 2 entries s̶h̶o̶u̶l̶d̶ fixes the problem (I removed the one from autostart). If you know the line/file, I can test this one too in QTCreator.

This is the last minor bug I have on my end. Cheers

**Comment by Shatur** [comment]
Thank you for your attention to my project :)

To autostart with system, the program only copies `/usr/share/applications/optimus-manager-qt.desktop` to `~/.config/autostart/optimus-manager-qt.desktop` in [this](https://github.com/Shatur95/optimus-manager-qt/blob/74126c7986c7e1ea4b8ba598eeeb99418b3e34cd/src/appsettings.cpp#L61) function. So, logic look good for me.
But maybe need to change something in `.desktop` file? How XFCE adds programs to run with session?

**Comment by Zeioth** [comment]
Your shortcut works correctly. I just realized i had checked the checkbox "Restore session" in XFCE. This opens all your programs from the previous session every time you start your computer, which is very convenient. After disabling this option i don't experience the issue anymore.

![sterf](https://user-images.githubusercontent.com/3357792/56459890-8b9dd180-639a-11e9-8d5d-d5d711c44c5e.png)

I see two options:

* Ignore the issue, since it's not a big deal.
* Or even better, remove the msg box that is shown when optimus-manager-qt is already running.

You decide! Cheers.

**Comment by Shatur** [comment]
I decided to remove this message as in other apps.

I also noticed that you are using spanish in your system. Maybe you want to translate the application? Just open [this](https://github.com/Shatur95/optimus-manager-qt/blob/master/data/translations/optimus-manager.ts) file with Qt Linguist, edit, save as `optimus-manager_es.ts` and send me pull request.

**Comment by Zeioth** [comment]
Funny thing is, I was already doing it! I just sent you a pull request. I hope everything is ok. Cheers.
