### ISSUE TITLE
Wrong Icon Bug

### ISSUE THREAD

**Issue by kingavatar** [Shatur/optimus-manager-qt#81]
**Bug description**
The Optimus Manager Qt is displaying hybrid icon when the GPU mode is Nvidia.

The output of `optimus-manager --print-mode` is `Current GPU mode : nvidia`

**Expected behavior**
To Display the Nvidia icon on nvidia mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/31726036/104043887-7f0e7c00-5202-11eb-85d0-972214f485f5.png)
![image](https://user-images.githubusercontent.com/31726036/104043923-89307a80-5202-11eb-98ef-1f6aa5f3e4a6.png)

**Environment**

-   OS: Manjaro
-   Desktop environment: KDE
-   Optimus Manager version: 1.3
-   Optimus Manager Qt version: 1.5.3

**Additional context**
On printing the gpuName in detectGpu method i found it is showing both gpu names even when the Current Gpu Mode is Nvidia according to optimus-manager.
![image](https://user-images.githubusercontent.com/31726036/104044232-078d1c80-5203-11eb-8d8b-5ccff2d1d3c9.png)

**Comment by Shatur** [comment]
This is strange. You have `modesetting`, which an integrated card. Maybe this is an `optimus-manager` bug?

**Comment by kingavatar** [comment]
The `nvidia` card is definitely being used as primary card here. As for why `modesetting` is also being displayed may be a bug from the manager.

**Comment by Shatur** [comment]
Okay, I will change detection mechanism according to optimus manager.

> As for why modesetting is also being displayed may be a bug from the manager.

Currently I use syscalls to detect GPU. And you have two GPUs enabled. Strange.

**Comment by kingavatar** [comment]
Yeah although only `nvidia` is being used, both gpu's are active.

**Comment by Shatur** [comment]
Should be okay now. Sorry for the delay.

**Comment by kingavatar** [comment]
Thank you. It is working perfectly now.
