### ISSUE TITLE
Launch at startup is not being saved

### ISSUE THREAD

**Issue by diegodorado** [Shatur/optimus-manager-qt#82]
In the settings panel, launch at startup is not being saved.

**Steps to reproduce**

1.  Go to Settings
2.  Check "launch at startup"
3.  Close the panel
4.  Exit
5. Re-open optimus manager qt
6. Open settings, to see "launch at startup" is still unchecked

**Environment**

-   OS: Manjaro
-   Window Manager: i3
-   Optimus Manager version: 1.3.1
-   Optimus Manager Qt version: 1.5.3

**Comment by Shatur** [comment]
Already fixed in the latest master. Duplicate of #65.
Just waiting for Optimus Manager release to draft a new version of GUI.
