### ISSUE TITLE
The specified icon for prime-hybrid for the current gpu is invalid

### ISSUE THREAD

**Issue by killajoe** [Shatur/optimus-manager-qt#83]
**Bug description**
using master branch to build package on arch based Distro (EndeavourOS) works fine, but it shows an error that the icon:
prime-hybrid can not be found:
![image](https://user-images.githubusercontent.com/16797647/107097738-e6bde400-680d-11eb-879c-fe5d05480a6d.png)
Icon set in use is breeze, but it shows the same on other default icon themes.

**Steps to reproduce**

1.  edit PKGBUILD to enable PLASMA feature
2.  build and install  package with makepkg -si
3.  check if optimus-manager is running (systemctl status optimus-manager)
4.  start the app

**Expected behavior**
icons are available and show up

**Screenshots**
![image](https://user-images.githubusercontent.com/16797647/107097738-e6bde400-680d-11eb-879c-fe5d05480a6d.png)

**Environment**
PLASMA (from archlinux repositories) installed on EndeavourOS

-   Desktop environment: (e.g. KDE, GNOME)
-   optimus-manager-git  1.3.1.r51.gd79cb51-1
-   optimus-manager-qt-git  1.5.3.r62.ga35fe7f-1

**Additional context**
see here:
https://forum.endeavouros.com/t/cant-boot-os/11742/31

**Comment by Shatur** [comment]
The icon just not exists in Breeze. Just navigate to the application settings and change the icon.

**Comment by Shatur** [comment]
But yes, these icons should be bundled. I'll fix it tomorrow.

**Comment by killajoe** [comment]
thanks for looking into this! 
I see that source only have one icon and most icon themes have no one for it, I do only see this on Papirus 
`/Papirus/24x24/panel/prime-hybrid.svg`

**Comment by Shatur** [comment]
Done!

**Comment by killajoe** [comment]
Is there a still difference between the stable release and master branch on supported GPUS ? i read somehow AMD was not supported before?
We think about adding this as packages to EndeavourOS Repository for a more easy install of optimus/prime systems, and I am not sure if we need the git version or not.

**Comment by killajoe** [comment]
![icon-shows-up](https://user-images.githubusercontent.com/16797647/107127826-0d852480-68b9-11eb-8491-9aad55d152a0.png)

it is working now!

**Comment by Shatur** [comment]
> Is there a still difference between the stable release and master branch on supported GPUS ? i read somehow AMD was not supported before?

Yes, AMD currently supported only on the latest master. The new release will be available when the [Optimus Manager](https://github.com/Askannz/optimus-manager) is released.

> it is working now!

Nice to hear.
