### ISSUE TITLE
Broken icons on Plasma 5.21

### ISSUE THREAD

**Issue by michaldybczak** [Shatur/optimus-manager-qt#84]
With Plasma 5.21 it looks like the package lost its ability to use the icons from the desktop theme and reverted to the default icon. Moreover, it was nvidia green icon for all the modes, so I couldn't know which GPU mode is currently on.

I recompiled the package, restarted, and now it shows correctly various mode icons: intel, blue-hybrid, green-nvidia. However, this is still the default icon, not from the desktop theme.

I cannot post any images as the new Plasma broke the ability to drag and drop images :( and I can't see a way to add images here. I already submitted a bug to Plasma bugzilla about it.

**Comment by Shatur** [comment]
I am also using Plasma 5.21 and the icons display correctly on the latest master and latest release. So, I think that the issue in your system configuration.

**Comment by michaldybczak** [comment]
Hm... Possible, but I haven't changed optimus-manager-qt configuration. However, I changed theming, although went back to the previous one, so it should prevent to the previous state, but it didn't. Also, it showed the same green nvidia icon for:
prime-intel
prime-nvidia
prime-hybrid
Only after recompiling it shows correctly different icons, but still the default ones, not from the desktop theme.
I will experiment a bit and return with the report.

**Comment by Shatur** [comment]
>  Possible, but I haven't changed optimus-manager-qt configuration. 

I meant system configuration. Something definitely wrong on you side.

> Only after recompiling it shows correctly different icons, but still the default ones, not from the desktop theme.

As a temporary workaround you can specify full path to the icon.

**Comment by michaldybczak** [comment]
I checked various desktop themes and various icon themes. Nothing changes the icon in optimus-manager-qt now.
Previously, on some desktop themes I had the default icons (intel, green-nvidia, blue-nvidia set) but some themes triggered other icons (monochromatic). At the moment there are no monochromatic ones from any of the destkop themes.

If you say "cons display correctly" what do you mean exactly? Did you refer to the issue where all modes were showing the same icon or maybe that it does have different icons on various themes? If your current theme is showing you default icon combo (which most themes do) then you are not noticing the issue I am talking about.

So basically, there are two issues:

1. **One icon for all GPU modes** - this could have been caused by the fact that I didn't recompile the package from a long time and this update triggered something. You probably didn't have this issue, because your version was much more recent and closer to git master. Anyway, forget that problem. Recompilation is needed once in a while anyway. It will be more important if users having a precompiled package will report the same problem, then the release bump will be a quick solution. No need to discuss it here any further.
2. **Default icon set used for all the time, optimus-manager-qt is unable to use desktop theme related icons anymore if available.**
Are you aware of a desktop theme that should have use other icon set? Can you check if it does display correctly on your side?

I can't say for sure, but I believe I was using Whitesur Dark theme and it did have unique icons.

How do I add images here? I could post a screenshot how the icon used to look like for me. Since drag and drop isn't working, and I'm too lazy to use imgur, I "can't" post images here ;).

This issue is not a big deal for me. I like the default icons. I don't need to set custom paths to icons. I'm just concerned that the update resulted in regression and only few users could have spotted it. Like I said, most themes triggered default icons, so the issue would be not noticeable for them.

EDIT: I browsed icons on desktop themes I have in the system and I can't find icons that were previously used by optimus-manager-qt. Am I looking in the wrong place?
`
~/.local/share/plasma/desktoptheme/`

and there in folder theme icons.

Do I understand it correctly, the additional icons should be there? If they weren't there in the first place, where did I get those icons before? Hmm... Or maybe those came from icon theme? I checked those, but they often don't load correctly until session is re-launched, so I could have missed something.

EDIT 2:

**Found it! It was icon theme after all, not desktop theme! McMuse-circle-dark added the icon I had before. So all is working... false alarm ;P. Sorry to take your time. I'm closing the case, all is fine :).**

P.S. This is quite confusing that most icons comes from desktop theme but some tray icons come from icon theme... One learns the Plasma complicated ways all the time.

**Comment by Shatur** [comment]
> Did you refer to the issue where all modes were showing the same icon or maybe that it does have different icons on various themes? If your current theme is showing you default icon combo (which most themes do) then you are not noticing the issue I am talking about.

I meant both :) I use Papirus Icon theme and have different icons from it. Other themes that do not have such icons just use my default GPU icons that installed with the application.

> How do I add images here? I could post a screenshot how the icon used to look like for me. Since drag and drop isn't working, and I'm too lazy to use imgur, I "can't" post images here ;).

You can just copy a screenshot to clipboard and use <kbd>Ctrl</kbd> + <kbd>V</kbd>.

> Found it! It was icon theme after all, not desktop theme! McMuse-circle-dark added the icon I had before. So all is working... false alarm ;P. Sorry to take your time. I'm closing the case, all is fine :).

I'm glad the problem was resolved.

> P.S. This is quite confusing that most icons comes from desktop theme but some tray icons come from icon theme... One learns the Plasma complicated ways all the time.

If it's an app, then it uses an icon theme, and if it's a widget, then it uses a Plasma theme.

**Comment by michaldybczak** [comment]
> If it's an app, then it uses an icon theme, and if it's a widget, then it uses a Plasma theme.

Ah, thanks for the explanation :).
