### ISSUE TITLE
Integrated graphics icon looks too big

### ISSUE THREAD

**Issue by adamraine** [Shatur/optimus-manager-qt#87]
**Bug description**
Integrated graphics icon looks a little too big in a thin KDE latte dock. It might just be the icon design, but I think it stands out a little too much.

**Steps to reproduce**

1. Install on KDE with latte dock
2. Put system tray in latte panel
3. Set item size to 22px absolute in the panel settings

**Expected behavior**
Icon is comparable in size to other tray icons.

**Screenshots**
![Screenshot_20210306_152728](https://user-images.githubusercontent.com/6752989/110219965-78158a00-7e90-11eb-9f09-a84260a1d2db.png)

**Environment**

-   OS: Arch Linux
-   Desktop environment: KDE
-   Optimus Manager version: 1.4
-   Optimus Manager Qt version: 1.6.0

**Comment by Shatur** [comment]
I think this is not an application problem. Other icons on screenshot are applets and just have a different size. There is nothing that I can do here :(

**Comment by Shatur** [comment]
BTW, I think it worth to report the issue to the Plasma itself.

**Comment by adamraine** [comment]
Thanks, will do.
