### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by blackPantherOS** [Shatur/optimus-manager-qt#88]
**Bug description**

New version: 1.6.0
Missing device icons on sidebar of settings dialog. (appearance in previous versions was good of icons) 
![image](https://user-images.githubusercontent.com/12883566/110232026-69c08000-7f1b-11eb-813d-6342009f0d1a.png)

**Comment by Shatur** [comment]
The problem is with the icon theme.
Previously I bundled all icons, but then decided to bundle only status icons. Probably I should reconsider this.

**Comment by blackPantherOS** [comment]
> Previously I bundled all icons, but then decided to bundle only status icons. Probably I should reconsider this.

Thanks, I think so the bundled icons better solution for non system applications. 
Maybe a good idea a selectable switch in cmake config for developers, example:

WITH_SYSTEM_ICONS
WITHOUT_SYSTEM_ICONS

**Comment by Shatur** [comment]
I decided to bundle GPU icons by default.
