### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by linuxergr** [Shatur/optimus-manager-qt#90]
**Bug description**
makefile error

**Steps to reproduce**
Download either the git master or the latest release, and try to build it.

**Expected behavior**
`[ 30%] Automatic RCC for _deps/circleflags-src/flags/flags.qrc
/bin/sh: -c: line 1: syntax error near unexpected token `('
/bin/sh: -c: line 1: `/usr/bin/cmake -E cmake_autorcc /home/linuxer/GITs/Artix/artools-workspace/optimus-manager-qt\ (copy\ 1)/git/optimus-manager-qt/build/CMakeFiles/optimus-manager-qt_autogen.dir/AutoRcc_flags_XI3V7B3WR2_Info.json '
make[2]: *** [CMakeFiles/optimus-manager-qt.dir/build.make:129: optimus-manager-qt_autogen/XI3V7B3WR2/qrc_flags.cpp] Error 2
make[1]: *** [CMakeFiles/Makefile2:117: CMakeFiles/optimus-manager-qt.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

`

**Environment**

-   OS: Artix Linux
-   Optimus Manager Qt version:1.6.0
-   Qt 5.15.2

**Comment by Shatur** [comment]
Can't reproduce on my side. Could you send me a file with the full log?

**Comment by linuxergr** [comment]
Yup, here are the logs of both cmake and make

[cmake.log](https://github.com/Shatur95/optimus-manager-qt/files/6143118/cmake.log)

[make.log](https://github.com/Shatur95/optimus-manager-qt/files/6143120/make.log)

**Comment by Shatur** [comment]
This line:

```
/bin/sh: -c: line 1: syntax error near unexpected token `('
```

says that your source path (`/home/linuxer/GITs/Artix/artools-workspace/optimus-manager-qt (copy 1)/git/optimus-manager-qt`) contains `(`. Try to build with a path without braces.

**Comment by linuxergr** [comment]
Yup, it worked :D 

Thnx, I missed that point.
