### ISSUE TITLE
No icon on taskbar

### ISSUE THREAD

**Issue by ginick** [Shatur/optimus-manager-qt#93]
in ver. 1.6.1-1_with_plasma=true/Optimus Manager version: 1.4-1
on KDE plasma 5.21.3/Manjaro
i have no icon in the panel,
in settings,integreted/nvidia/hybrid all default to the nvidia icon,
and trying to set manually to another icon,brings an error:(in the screenshot it's on intel,but that's just before i get the following error)
The specified icon 'prime-nvidia' for the current GPU is invalid. The default icon will be used.
it also defaults on boot,and logging in after logging out creates a long hang)
i use the "beautyline" icon pack as default.

![Screenshot_20210403_223657](https://user-images.githubusercontent.com/81878623/113489612-e2403f80-94cd-11eb-8c79-1019e9bf1191.png)
![Screenshot_20210403_223744](https://user-images.githubusercontent.com/81878623/113489618-e79d8a00-94cd-11eb-9a43-39e3bd8000c9.png)

**Comment by Shatur** [comment]
Reproduced. I did not notice it before because the problem is visible only on some icon themes.

**Comment by Shatur95** [comment]
Reproduced. I did not notice it before because the problem is visible only on some icon themes.

**Comment by Shatur95** [comment]
Reproduced. I did not notice it before because the problem is visible only on some icon themes.

**Comment by ginick** [comment]
it seems to be fixed for me.
Thanks!
