### ISSUE TITLE
v1.6.2 Format Error

### ISSUE THREAD

**Issue by quinnjr** [Shatur/optimus-manager-qt#94]
**Bug description**

Building `optimus-manager-qt` throws the following warning on my system:

```
/home/joseph/.cache/yay/optimus-manager-qt/src/optimus-manager-qt-1.6.2/src/optimusmanager.cpp:401:39: warning: incomplete format specifier [-Wformat]
            qFatal("Unknown provider: %1", gpuName);
```

And errors with:

```
/home/joseph/.cache/yay/optimus-manager-qt/src/optimus-manager-qt-1.6.2/src/optimusmanager.cpp:401:44: error: cannot pass object of non-trivial type 'const QByteArray' through variadic method; call will abort at runtime [-Wnon-pod-varargs]
            qFatal("Unknown provider: %1", gpuName);
```

**Steps to reproduce**

1.  Initiate build
2.  See error

**Environment**

-   OS: Arch Linux 5.11.16-arch1-1
-   Desktop environment: Cinnamon
-   Optimus Manager version: 1.4
-   Optimus Manager Qt version: 1.6.2

**Comment by Shatur** [comment]
Thanks for the report, I have not tried building a project with Clang before and did not know about the error.

**Comment by quinnjr** [comment]
When you have a chance, can you please bump the patch version so the AUR package gets updated?

**Comment by Shatur** [comment]
@quinnjr, okay, done!
