### ISSUE TITLE
Add wayland support 

### ISSUE THREAD

**Issue by jorge1b3** [Shatur/optimus-manager-qt#96]
**Describe the problem or limitation you are having**
With the Nvidia 470 diver, Wayland is now supported for Nvidia. Optimus manager command tool work well, but optimus manager qt sen a core dump "Cannot start in non-X11 session".

**Additional context**
I'm a novice in English, sorry if I don't express myself well.

**Comment by Shatur** [comment]
But optimus manager [README](https://github.com/Askannz/optimus-manager/#optimus-manager) says "Only Xorg sessions are supported (no Wayland)." Are you sure that it works for you on Wayland?

**Comment by jorge1b3** [comment]
While the support is not official, I can confirm that it works

**Comment by Shatur** [comment]
@jorge1b3, okay! I checked, `optimus-manager` currently just [warns about it](https://github.com/Askannz/optimus-manager/blob/master/optimus_manager/client/client_checks.py#L94). Should I use a warning too?
Could you also open an issue in https://github.com/Askannz/optimus-manager/ about it?

**Comment by Shatur** [comment]
Oh, I do exactly the same thing:

https://github.com/Shatur/optimus-manager-qt/blob/bc293575abb266c26a20d67d9c55c074b0ca98a0/src/optimusmanager.cpp#L274

The problem was with the detection algorithm that was using X11 API. Fixed.
