### ISSUE TITLE
Installer stuck at "Detecting CXX compile features - done"

### ISSUE THREAD

**Issue by saileshbro** [Shatur/optimus-manager-qt#99]
**Installer stuck**
I tried to install from AUR `yay -S optimus-manager-qt` but it seems to be stuck in this phase.

![image](https://user-images.githubusercontent.com/43571990/130556981-bda4fc84-4289-452a-ae04-1254c601c72e.png)

**Environment**

-   OS: Manjaro
-   Desktop environment: XFCE
-   Optimus Manager version: 1.4

**Comment by saileshbro** [comment]
This issue is related to [this](https://github.com/Askannz/optimus-manager/issues/279) bug. Fixed after fixing that.

**Comment by Shatur** [comment]
> This issue is related to this bug. Fixed after fixing that.

I think it's unrelated. You just have to wait for some time to let CMake download dependencies.
